module HistoriaClinicaDecorator


  	def select_condition
    	[
	        ['Pasajero', 'Pasajero'],
	        ['Tripulante', 'Tripulante'],
	        ['Empleado', 'Empleado'],
	        ['Visitante', 'Visitante'],
	        ['Otro', 'Otro']

    	]
  	end




  	def select_type_service
    	[
	        ['Atención prehospitalaria', 'Atención prehospitalaria'],
	        ['Valoración aptitud de vuelo', 'Valoración aptitud de vuelo'],
	        ['Enfermedad general', 'Enfermedad general'],
	        ['Evento laboral', 'Evento laboral'],
	        ['Accidente de transito', 'Accidente de transito'],
	        ['Traslado', 'Traslado'],
	        ['Otro tipo de accidente', 'Otro tipo de accidente'],
	        ['Remisión', 'Remisión']
    	]
  	end


  	def select_lugar
    	[
	        ['Interno(Sanidad)', 'Interno(Sanidad)'],
	        ['Externo', 'Externo'],
    	]
  	end

  	def select_pais
    	[
	        ['Afganistán', 'Afganistán'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Albania', 'Albania'],
	        ['Alemania', 'Alemania'],
	        ['Andorra', 'Andorra'],
	        ['Angola', 'Angola'],
	        ['Anguila', 'Anguila'],
	        ['Antártida', 'Antártida'],
	        ['Antigua y Barbuda', 'Antigua y Barbuda'],
	        ['Antillas Neerlandesas', 'Antillas Neerlandesas'],
	        ['Arabia Saudí', 'Arabia Saudí'],
	        ['Arctic Ocean', 'Arctic Ocean'],
	        ['Argelia', 'Argelia'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri'],
	        ['Akrotiri', 'Akrotiri']
    	]
  	end


end