Aeropuerto.create!([
  {nombre: "Aeropuerto Jerónimo De Aguaya", ciudad_id: 1, departamento: "Sandanter"},
  {nombre: "Aeropuerto Aguas Claras", ciudad_id: 2, departamento: "Norte De Santander"},
  {nombre: "Aeropuerto Alberto Lleras Camargo", ciudad_id: 3, departamento: "Boyaca"},
  {nombre: "Aeropuerto Alcides Fernández", ciudad_id: 4, departamento: "Choco"},
  {nombre: "Aeropuerto Alfonso López Pumarejo", ciudad_id: 5, departamento: "Cesar"},
  {nombre: "Aeropuerto Antonio Nariño", ciudad_id: 6, departamento: "Nariño"},
  {nombre: "Aeropuerto Antonio Roldán Betancourt", ciudad_id: 7, departamento: "Antioquia"},
  {nombre: "Aeropuerto Baracoa De Magangué", ciudad_id: 8, departamento: "Bolivar"},
  {nombre: "Aeropuerto Benito Salas", ciudad_id: 9, departamento: "Huila"},
  {nombre: "Aeropuerto Caucaya", ciudad_id: 10, departamento: "Putumayo"},
  {nombre: "Aeropuerto César Gaviria Trujillo", ciudad_id: 11, departamento: "Guania"},
  {nombre: "Aeropuerto Contador", ciudad_id: 12, departamento: "Huila"},
  {nombre: "Aeropuerto Cravo Norte", ciudad_id: 13, departamento: "Arauca"},
  {nombre: "Aeropuerto Cumaribo", ciudad_id: 14, departamento: "Vichada"},
  {nombre: "Aeropuerto De Araracuara", ciudad_id: 15, departamento: "Caqueta"},
  {nombre: "Aeropuerto De Capurganá", ciudad_id: 16, departamento: "Choco"},
  {nombre: "Aeropuerto De Juanchaco Buenaventura Valle Del Cauca ", ciudad_id: 17, departamento: "Valle Del Cauca"},
  {nombre: "Aeropuerto De La Chorrera Lcr  La Chorrera Amazonas 00°43'58?S 73°01'01?O ", ciudad_id: 18, departamento: "Amazonas"},
  {nombre: "Aeropuerto De La Macarena Lmc  La Macarena Meta 03°19'01?S 73°54'00?O", ciudad_id: 19, departamento: "Meta"},
  {nombre: "Aeropuerto De La Nubia", ciudad_id: 20, departamento: "Caldas"},
  {nombre: "Aeropuerto De Necoclí", ciudad_id: 21, departamento: "Antioquia"},
  {nombre: "Aeropuerto De Otú", ciudad_id: 22, departamento: "Antioquia"},
  {nombre: "Aeropuerto De Pizarro Pizarro Chocó", ciudad_id: 23, departamento: "Choco"},
  {nombre: "Aeropuerto De Puerto Rico Prj  Puerto Rico Caquetá 01°52'30?N 75°09'20?O", ciudad_id: 24, departamento: "Caqueta"},
  {nombre: "Aeropuerto De Timbiquí Timbiquí Cauca", ciudad_id: 25, departamento: "Cauca"},
  {nombre: "Aeropuerto De Villa Garzón", ciudad_id: 26, departamento: "Putumayo"},
  {nombre: "Aeropuerto Eduardo Falla Solano", ciudad_id: 27, departamento: "Caqueta"},
  {nombre: "Aeropuerto El Alcaraván", ciudad_id: 28, departamento: "Casanare"},
  {nombre: "Aeropuerto El Caraño", ciudad_id: 29, departamento: "Choco"},
  {nombre: "Aeropuerto El Embrujo", ciudad_id: 30, departamento: "San Andres Y Providencia"},
  {nombre: "Aeropuerto El Pindo", ciudad_id: 31, departamento: "Cordoba"},
  {nombre: "Aeropuerto El Tomin", ciudad_id: 32, departamento: "Antioquia"},
  {nombre: "Aeropuerto El Triunfo  Sk-415 Puerto Triunfo Antioquia 04°52'N 74°48'O", ciudad_id: 33, departamento: "Antioquia"},
  {nombre: "Aeropuerto Fabio Alberto León Bentley", ciudad_id: 34, departamento: "Vaupes"},
  {nombre: "Aeropuerto Gabriel Vargas Santos", ciudad_id: 35, departamento: "Arauca"},
  {nombre: "Aeropuerto Gerardo Tobar López", ciudad_id: 36, departamento: "Valle Del Cauca"},
  {nombre: "Aeropuerto Germán Olano", ciudad_id: 37, departamento: "Vichada"},
  {nombre: "Aeropuerto Golfo De Morrosquillo", ciudad_id: 38, departamento: "Sucre"},
  {nombre: "Aeropuerto Gonzalo Mejía", ciudad_id: 39, departamento: "Antioquia"},
  {nombre: "Aeropuerto Guaymaral", ciudad_id: 40, departamento: "Cundinamarca"},
  {nombre: "Aeropuerto Guillermo Gaviria Correa   Frontino Antioquia", ciudad_id: 41, departamento: "Antioquia"},
  {nombre: "Aeropuerto Guillermo León Valencia", ciudad_id: 42, departamento: "Cauca"},
  {nombre: "Aeropuerto Gustavo Artunduaga", ciudad_id: 43, departamento: "Caqueta"},
  {nombre: "Aeropuerto Gustavo Rojas Pinilla  Sktj Tunja Boyacá 05°32'28.98?N 73°20'40.18?O", ciudad_id: 44, departamento: "Boyaca"},
  {nombre: "Aeropuerto Heriberto Gil Martínez", ciudad_id: 45, departamento: "Valle Del Cauca"},
  {nombre: "Aeropuerto Internacional Alfonso Bonilla Aragón", ciudad_id: 46, departamento: "Valle Del Cauca"},
  {nombre: "Aeropuerto Internacional Alfredo Vásquez Cobo", ciudad_id: 47, departamento: "Amazonas"},
  {nombre: "Aeropuerto Internacional Almirante Padilla", ciudad_id: 48, departamento: "La Guajira"},
  {nombre: "Aeropuerto Internacional Camilo Daza", ciudad_id: 49, departamento: "Norte De Santander"},
  {nombre: "Aeropuerto Internacional Del Café   Manizales / Palestina Caldas 05°01'21?N 75°36'55?O", ciudad_id: 50, departamento: "Caldas"},
  {nombre: "Aeropuerto Internacional El Dorado (37) Bog Skbo Bogotá Distrito Capital 04°42'05.74?N 74°08'49.01?O", ciudad_id: 51, departamento: "Bogota D.C."},
  {nombre: "Aeropuerto Internacional El Edén (1) Axm Skar Armenia / La Tebaida Quindío 04°27'09.99?N 75°45'59.21?O", ciudad_id: 52, departamento: "Quindio"},
  {nombre: "Aeropuerto Internacional Ernesto Cortissoz", ciudad_id: 53, departamento: "Barranquilla"},
  {nombre: "Aeropuerto Internacional Gustavo Rojas Pinilla", ciudad_id: 54, departamento: "San Andres Y Providencia"},
  {nombre: "Aeropuerto Internacional José María Córdova", ciudad_id: 55, departamento: "Rio Negro Antioquia"},
  {nombre: "Aeropuerto Internacional Matecaña (1) Pei Skpe Pereira Risaralda 04°48'45.63?N 75°44'22.27?O", ciudad_id: 56, departamento: "Risaralda"},
  {nombre: "Aeropuerto Internacional Palonegro", ciudad_id: 57, departamento: "Santander"},
  {nombre: "Aeropuerto Internacional Rafael Núñez", ciudad_id: 58, departamento: "Bolivar"},
  {nombre: "Aeropuerto Internacional Simón Bolivar", ciudad_id: 59, departamento: "Magadalena"},
  {nombre: "Aeropuerto Jaime Ortís Betancur", ciudad_id: 60, departamento: "Antioquia"},
  {nombre: "Aeropuerto Jorge Enrique González", ciudad_id: 61, departamento: "Guaviare"},
  {nombre: "Aeropuerto Jorge Isaacs", ciudad_id: 62, departamento: "La Guajira"},
  {nombre: "Aeropuerto Jose Celestino Mutis", ciudad_id: 63, departamento: "Choco"},
  {nombre: "Aeropuerto Juan Casiano", ciudad_id: 64, departamento: "Cauca"},
  {nombre: "Aeropuerto Juan H. White", ciudad_id: 65, departamento: "Antioquia"},
  {nombre: "Aeropuerto Juan José Rondón Pya Skpa Paipa Boyacá 08°18'54.22?N 73°21'29.99?O", ciudad_id: 66, departamento: "Boyaca"},
  {nombre: "Aeropuerto La Arrobleda", ciudad_id: 67, departamento: "Cauca"},
  {nombre: "Aeropuerto La Florida", ciudad_id: 68, departamento: "Nariño"},
  {nombre: "Aeropuerto La Majayura", ciudad_id: 69, departamento: "La Guajira"},
  {nombre: "Aeropuerto Las Brujas", ciudad_id: 70, departamento: "Coral Sucre"},
  {nombre: "Aeropuerto Los Colonizadores", ciudad_id: 71, departamento: "Cauca"},
  {nombre: "Aeropuerto Los Garzones", ciudad_id: 72, departamento: "Cordoba"},
  {nombre: "Sgl Sksg San Gil Santander 06°35'25?N 73°07'44?O", ciudad_id: 73, departamento: "Santander"},
  {nombre: "Aeropuerto Mandinga", ciudad_id: 74, departamento: "Choco"},
  {nombre: "Aeropuerto Mariquita", ciudad_id: 75, departamento: "Tolima"},
  {nombre: "Aeropuerto Militar Catam Bog  Bogotá Distrito Capital", ciudad_id: 76, departamento: "Bogota D.C."},
  {nombre: "Aeropuerto Morelia", ciudad_id: 77, departamento: "Meta"},
  {nombre: "Aeropuerto Olaya Herrera", ciudad_id: 78, departamento: "Antioquia"},
  {nombre: "Aeropuerto Perales", ciudad_id: 79, departamento: "Tolima"},
  {nombre: "Aeropuerto Puerto Bolívar", ciudad_id: 80, departamento: "Uribia La Guajira"},
  {nombre: "Aeropuerto Reyes Murillo", ciudad_id: 81, departamento: "Choco"},
  {nombre: "Aeropuerto San Luis", ciudad_id: 82, departamento: "Nariño"},
  {nombre: "Aeropuerto San Pedro De Urabá", ciudad_id: 83, departamento: "Antioquia"},
  {nombre: "Aeropuerto Santa Ana", ciudad_id: 84, departamento: "Valle Del Cauca"},
  {nombre: "Aeropuerto Santiago Pérez", ciudad_id: 85, departamento: "Arauca"},
  {nombre: "Aeropuerto Santiago Vila", ciudad_id: 86, departamento: "Tolima"},
  {nombre: "Aeropuerto Tres De Mayo", ciudad_id: 87, departamento: "Putumayo"},
  {nombre: "Aeropuerto Vanguardia", ciudad_id: 88, departamento: "Meta"},
  {nombre: "Aeropuerto Yariguíes", ciudad_id: 89, departamento: "Santander"},
  {nombre: "Base Aérea De Madrid  Skma Madrid Cundinamarca 04°43'40.08?N 74°16'31.38?O", ciudad_id: 90, departamento: "Cundinamarca"},
  {nombre: "Base Aérea De Marandúa", ciudad_id: 91, departamento: "Guaviare"},
  {nombre: "Base Aérea De Tolemaida Melgar Tolima", ciudad_id: 92, departamento: "Tolima"},
  {nombre: "Base Aérea De Tres Esquinas", ciudad_id: 93, departamento: "Caqueta"},
  {nombre: "Base Aérea Germán Olano (Palanquero)", ciudad_id: 94, departamento: "Cundinamarca"},
  {nombre: "Base Aérea Larandia  Sklr Florencia Caquetá 01°28'44.71?N 75°29'12.34?O", ciudad_id: 95, departamento: "Caqueta"},
  {nombre: "Base Aérea Marco Fidel Suárez  Skgb Santiago De Cali Valle Del Cauca 03°27'32?N 076°29'47?O", ciudad_id: 96, departamento: "Valle Del Cauca"},
  {nombre: "Terminal Puente Aéreo Bog Skbo Bogotá Distrito Capital 04°42'05.74?N 74°08'49.01?O", ciudad_id: 97, departamento: "Bogota D.C."},
])