Aeropuerto.create!([
  {nombre: "BAGRAM", ciudad_id: 1},
  {nombre: "BAGUIO", ciudad_id: 2},
  {nombre: "BAHIAS DEHEATULCO", ciudad_id: 3},
  {nombre: "BALER INTERNATIONAL", ciudad_id: 4},
  {nombre: "BALMACEDA TENIENTE VICIAL", ciudad_id: 5},
  {nombre: "GHAZNI", ciudad_id: 6},
  {nombre: "HERAT", ciudad_id: 7},
  {nombre: "JALALABAD", ciudad_id: 8},
  {nombre: "KANDAHAR", ciudad_id: 9},
  {nombre: "KHWAJA RAWASH", ciudad_id: 10},
  {nombre: "MAZAR-E SARIF", ciudad_id: 11},
  {nombre: "SHANK AIRBASE", ciudad_id: 12},
  {nombre: "SHARANA", ciudad_id: 13},
  {nombre: "SHINDAND AIR BASE", ciudad_id: 14},
  {nombre: "CAPE TOWN INTL", ciudad_id: 15},
  {nombre: "HOUARI BOUMEDIENE", ciudad_id: 16},
  {nombre: "KOTAKA", ciudad_id: 17},
  {nombre: "MESSINA", ciudad_id: 18},
  {nombre: "MONROVIA ROBERTS", ciudad_id: 19},
  {nombre: "FRANKFURT HAHN", ciudad_id: 20},
  {nombre: "FRANKFURT MAIN", ciudad_id: 21},
  {nombre: "FUHLSBUETTEL", ciudad_id: 22},
  {nombre: "KOHL", ciudad_id: 23},
  {nombre: "TEGEL", ciudad_id: 24},
  {nombre: "DUSSELDORT INTER", ciudad_id: 25},
  {nombre: "STUTTGART - WURTTEMBERG", ciudad_id: 26},
  {nombre: "4 DE FEVEREIRO", ciudad_id: 27},
  {nombre: "GRAND CASE,GUADELOU", ciudad_id: 28},
  {nombre: "LE RAIZET", ciudad_id: 29},
  {nombre: "FLAMINGO", ciudad_id: 30},
  {nombre: "HATO", ciudad_id: 31},
  {nombre: "PRINCESS JULIANA INTL", ciudad_id: 32},
  {nombre: "REINA BEATRIX INTL", ciudad_id: 33},
  {nombre: "KING KHA LED", ciudad_id: 34},
  {nombre: "SHARJAH INTER", ciudad_id: 35},
  {nombre: "AEROPUERTO JORGE NEWBERY", ciudad_id: 36},
  {nombre: "CAP.VICENTE ALMANDOS AMONACIDE", ciudad_id: 37},
  {nombre: "CATAMARCA", ciudad_id: 38},
  {nombre: "CATARATAS DEL IGUAZU", ciudad_id: 39},
  {nombre: "COMODORO RIVADARIA AERODROME", ciudad_id: 40},
  {nombre: "CORDOBA, CBA", ciudad_id: 41},
  {nombre: "CORRIENTES CAMBA PUNTA", ciudad_id: 42},
  {nombre: "EL CALAFATE", ciudad_id: 43},
  {nombre: "EL PALOMAR", ciudad_id: 44},
  {nombre: "EL PLUMILLERO", ciudad_id: 45},
  {nombre: "ESQUEL", ciudad_id: 46},
  {nombre: "GENERAL PICO", ciudad_id: 47},
  {nombre: "GRAL URQUIZAER", ciudad_id: 48},
  {nombre: "HERMES QUIJADA", ciudad_id: 49},
  {nombre: "JUJUY, J.", ciudad_id: 50},
  {nombre: "MAR DE LA PLATA", ciudad_id: 51},
  {nombre: "MINISTRO PISTARINI", ciudad_id: 52},
  {nombre: "NEUQUEN AERODROME", ciudad_id: 53},
  {nombre: "POSADAS", ciudad_id: 54},
  {nombre: "PUELCHES / LP", ciudad_id: 55},
  {nombre: "RESISTENCIA - CHO", ciudad_id: 56},
  {nombre: "ROSARIO SF", ciudad_id: 57},
  {nombre: "S.C.BARILOCHE", ciudad_id: 58},
  {nombre: "SALTA, S.", ciudad_id: 59},
  {nombre: "SAN JUAN AERODROME", ciudad_id: 60},
  {nombre: "SAN LUIS", ciudad_id: 61},
  {nombre: "SAN MARTIN DE LOS ANDES", ciudad_id: 62},
  {nombre: "TRELEW", ciudad_id: 63},
  {nombre: "TUCUMAN/TENENT MATIENZOT", ciudad_id: 64},
  {nombre: "USHUAIA TDE F.", ciudad_id: 65},
  {nombre: "VIEDMA", ciudad_id: 66},
  {nombre: "COMANDANTE ESPORA", ciudad_id: 67},
  {nombre: "SAN FERNADO INTERNATIONAL", ciudad_id: 68},
  {nombre: "NORTH LITTLE ROCK MUNI", ciudad_id: 69},
  {nombre: "YUMA MARINE CORPS AIR STATION", ciudad_id: 70},
  {nombre: "KINGSFORD SMITH", ciudad_id: 71},
  {nombre: "SCWECHAT", ciudad_id: 72},
  {nombre: "FREEPORT/INTL", ciudad_id: 73},
  {nombre: "MARSH HARBOUR", ciudad_id: 74},
  {nombre: "NASSAU INTL", ciudad_id: 75},
  {nombre: "ROCK SOUND", ciudad_id: 76},
  {nombre: "EXUMA ISLAND", ciudad_id: 77},
  {nombre: "SAN SALVADOR AIRPORT / COCKBUR", ciudad_id: 78},
  {nombre: "BRIDGETOWN CITY", ciudad_id: 79},
  {nombre: "GRANTLEY ADAMS INTL", ciudad_id: 80},
  {nombre: "BRUXELLES", ciudad_id: 81},
  {nombre: "LIEGE  BIERSET", ciudad_id: 82},
  {nombre: "OOSTENDE", ciudad_id: 83},
  {nombre: "ANTWERO", ciudad_id: 84},
  {nombre: "PHILIP S W GOLDSON INTL", ciudad_id: 85},
  {nombre: "COBIJA", ciudad_id: 86},
  {nombre: "EL ALTO INTERNACIONAL", ciudad_id: 87},
  {nombre: "EL TROMPILLO", ciudad_id: 88},
  {nombre: "EL TROMPILLO", ciudad_id: 89},
  {nombre: "GUAYARAMERIN", ciudad_id: 90},
  {nombre: "JORGE WILSTERMAN", ciudad_id: 91},
  {nombre: "TTE AV JORGE HENRICH ARAUZ", ciudad_id: 92},
  {nombre: "VIRU VIRU INTL", ciudad_id: 93},
  {nombre: "YACUBIA", ciudad_id: 94},
  {nombre: "AFONSO PENA", ciudad_id: 95},
  {nombre: "AUGUSTO SEVERO R.N", ciudad_id: 96},
  {nombre: "BOAVISTA", ciudad_id: 97},
  {nombre: "CABO FRIO", ciudad_id: 98},
  {nombre: "CAMPO  GRANDE", ciudad_id: 99},
  {nombre: "CATARATAS PR.", ciudad_id: 100},
  {nombre: "CONGONHAS", ciudad_id: 101},
  {nombre: "CRUZEIRO DO SUL", ciudad_id: 102},
  {nombre: "CUIABA", ciudad_id: 103},
  {nombre: "DE CAES", ciudad_id: 104},
  {nombre: "DOS DE JULIO", ciudad_id: 105},
  {nombre: "EDUARDO GOMES INTL", ciudad_id: 106},
  {nombre: "FORTALEZA", ciudad_id: 107},
  {nombre: "FOZ/TMA", ciudad_id: 108},
  {nombre: "GALEAO ANTONIO CARLOS JOBIM", ciudad_id: 109},
  {nombre: "GOIABEIRAS. ES", ciudad_id: 110},
  {nombre: "GOIANIA/SANTA GENOVEVA", ciudad_id: 111},
  {nombre: "GUARARAPES/PERMAMBUCO", ciudad_id: 112},
  {nombre: "GUARULHOS", ciudad_id: 113},
  {nombre: "HERCILIO LUZ", ciudad_id: 114},
  {nombre: "JOINVILLE -LAURO CARNEIRO", ciudad_id: 115},
  {nombre: "MARINGA", ciudad_id: 116},
  {nombre: "PAMPULHA", ciudad_id: 117},
  {nombre: "PETROLINA", ciudad_id: 118},
  {nombre: "PONTA PELADA", ciudad_id: 119},
  {nombre: "PORTO SEGURO", ciudad_id: 120},
  {nombre: "PORTO VELHO", ciudad_id: 121},
  {nombre: "PRESIDENTE CASTRO PINTO", ciudad_id: 122},
  {nombre: "PRESIDENTE JUSCELINO KUBITSCHE", ciudad_id: 123},
  {nombre: "PRESIDENTE MENICI", ciudad_id: 124},
  {nombre: "SALGADO FHILO", ciudad_id: 125},
  {nombre: "SAO GABRIEL DA CACHOEIRA", ciudad_id: 126},
  {nombre: "SAO JOSE DOS CAMPOS", ciudad_id: 127},
  {nombre: "TABATINGA", ciudad_id: 128},
  {nombre: "TANCREDO NEVES", ciudad_id: 129},
  {nombre: "TIRIRICAL", ciudad_id: 130},
  {nombre: "VIRACOPOS", ciudad_id: 131},
  {nombre: "CUMBICA INTERNATIONAL", ciudad_id: 132},
  {nombre: "JAGS McCARTNEY", ciudad_id: 133},
  {nombre: "EL CENTRO NAF", ciudad_id: 134},
  {nombre: "MC CLELLAN AIRFIELD", ciudad_id: 135},
  {nombre: "MOFFETT FEDERAL AFLD", ciudad_id: 136},
  {nombre: "MONTEREY", ciudad_id: 137},
  {nombre: "SACRAMENTO MATHER", ciudad_id: 138},
  {nombre: "VENTURA NAVAL AIR STATION", ciudad_id: 139},
  {nombre: " TRENTON", ciudad_id: 140},
  {nombre: "EDMONTON INTER", ciudad_id: 141},
  {nombre: "GANDER INTL, NFLD", ciudad_id: 142},
  {nombre: "GATINEAU", ciudad_id: 143},
  {nombre: "GOOSE INTER", ciudad_id: 144},
  {nombre: "GREATER FREDERICTON", ciudad_id: 145},
  {nombre: "GREATER SUDBURY", ciudad_id: 146},
  {nombre: "INTERNATIONAL ARMSTRONG", ciudad_id: 147},
  {nombre: "INTERNATIONAL ST. JONS", ciudad_id: 148},
  {nombre: "JAMES ARMSTRONG RICHARDSON", ciudad_id: 149},
  {nombre: "LESTER B PEARSON INTL", ciudad_id: 150},
  {nombre: "MONCTON", ciudad_id: 151},
  {nombre: "MONTREAL INTL MIRABEL", ciudad_id: 152},
  {nombre: "OTTAWA/MACDONALD - CARTIER INT", ciudad_id: 153},
  {nombre: "QUEBEC", ciudad_id: 154},
  {nombre: "VANCOUVER INTERNATIONAL", ciudad_id: 155},
  {nombre: "CALGARY INTL,ALTA", ciudad_id: 156},
  {nombre: "DORVAL", ciudad_id: 157},
  {nombre: "HALIFAX INTL. N. S.", ciudad_id: 158},
  {nombre: "IQALUIT", ciudad_id: 159},
  {nombre: "OTTAWA", ciudad_id: 160},
  {nombre: "SYDNEY, N.S.", ciudad_id: 161},
  {nombre: "AMILCAR CABRAL", ciudad_id: 162},
  {nombre: "SPARTANBUR", ciudad_id: 163},
  {nombre: "DUPAGE", ciudad_id: 164},
  {nombre: "AD EL LOA", ciudad_id: 165},
  {nombre: "AP.MATAVERI", ciudad_id: 166},
  {nombre: "ARTURO MERINO BENITEZ INTL", ciudad_id: 167},
  {nombre: "CARLOS IBAÑEZ DEL CAMPO", ciudad_id: 168},
  {nombre: "CARRIEL SU", ciudad_id: 169},
  {nombre: "CERRO MORENO", ciudad_id: 170},
  {nombre: "CHACALLUTA", ciudad_id: 171},
  {nombre: "EL TEPUAL", ciudad_id: 172},
  {nombre: "GRAL. DIEGO ARACENA", ciudad_id: 173},
  {nombre: "LA SERENA FLORIDA", ciudad_id: 174},
  {nombre: "LOS CERRILLOS", ciudad_id: 175},
  {nombre: "TALCA", ciudad_id: 176},
  {nombre: "TEMUCO", ciudad_id: 177},
  {nombre: "VIÑA DEL MAR", ciudad_id: 178},
  {nombre: "DESIERTO DE ATACAMA", ciudad_id: 179},
  {nombre: "PU DONG", ciudad_id: 180},
  {nombre: "ACANDI", ciudad_id: 181},
  {nombre: "AMALFI", ciudad_id: 182},
  {nombre: "ANDES", ciudad_id: 183},
  {nombre: "ANTONIO ROLDAN BETANCOURT", ciudad_id: 184},
  {nombre: "APIAY - FAC", ciudad_id: 185},
  {nombre: "ARARACUARA", ciudad_id: 186},
  {nombre: "SANTIAGO PEREZ QUIROZ", ciudad_id: 187},
  {nombre: "EL TRONCAL", ciudad_id: 188},
  {nombre: "EL EDEN", ciudad_id: 189},
  {nombre: "JOSE C. MUTIS", ciudad_id: 190},
  {nombre: "YARIGUIES", ciudad_id: 191},
  {nombre: "BARRANCO MINAS", ciudad_id: 192},
  {nombre: "ERNESTO. CORTISSOZ", ciudad_id: 193},
  {nombre: "BECERRIL", ciudad_id: 194},
  {nombre: "BERASTEGUI", ciudad_id: 195},
  {nombre: " ELDORADO", ciudad_id: 196},
  {nombre: "PALONEGRO", ciudad_id: 197},
  {nombre: "GERARDO TOBAR L", ciudad_id: 198},
  {nombre: "BUENAVISTA", ciudad_id: 199},
  {nombre: "CALENTURITAS", ciudad_id: 200},
  {nombre: "ALFONSO BONILLA ARAGON", ciudad_id: 201},
  {nombre: "CAÑO GANDUL", ciudad_id: 202},
  {nombre: "CAÑO GARZA", ciudad_id: 203},
  {nombre: "CAPURGANA", ciudad_id: 204},
  {nombre: "CARIMAGUA", ciudad_id: 205},
  {nombre: "CARMEN DE BOLIVAR", ciudad_id: 206},
  {nombre: "CARREÑO-GERMAN OLANO", ciudad_id: 207},
  {nombre: "CARTAGENA - RAFAEL NUÑEZ", ciudad_id: 208},
  {nombre: "CARURU", ciudad_id: 209},
  {nombre: "JUAN H. WHITE", ciudad_id: 210},
  {nombre: "NAVAS PARDO", ciudad_id: 211},
  {nombre: "JAIME ORTIZ BETANC", ciudad_id: 212},
  {nombre: "CICUCO", ciudad_id: 213},
  {nombre: "CIMITARRA GUSTAVO ROJAS", ciudad_id: 214},
  {nombre: "MANDINGA", ciudad_id: 215},
  {nombre: "COROCORA", ciudad_id: 216},
  {nombre: "LAS BRUJAS", ciudad_id: 217},
  {nombre: "COVEÑAS", ciudad_id: 218},
  {nombre: "CRAVO NORTE", ciudad_id: 219},
  {nombre: "CRUZ VERDE", ciudad_id: 220},
  {nombre: "CAMILO DAZA", ciudad_id: 221},
  {nombre: "CUMARIBO", ciudad_id: 222},
  {nombre: "CUPICA", ciudad_id: 223},
  {nombre: "CUSIANA", ciudad_id: 224},
  {nombre: "EL BAGRE", ciudad_id: 225},
  {nombre: "EL BANCO", ciudad_id: 226},
  {nombre: "EL BORAL", ciudad_id: 227},
  {nombre: "EL BORREGO", ciudad_id: 228},
  {nombre: "EL CHARCO", ciudad_id: 229},
  {nombre: "EL PACIFICO", ciudad_id: 230},
  {nombre: "EL VISO", ciudad_id: 231},
  {nombre: "EL YOPAL", ciudad_id: 232},
  {nombre: "FUNDACION", ciudad_id: 233},
  {nombre: "FURATENA", ciudad_id: 234},
  {nombre: "LA JAGUA", ciudad_id: 235},
  {nombre: "GIRARDOT SANTIAGO VILA", ciudad_id: 236},
  {nombre: "GUADALAJARA", ciudad_id: 237},
  {nombre: "GUAICARAMO", ciudad_id: 238},
  {nombre: "JUAN CASIANO", ciudad_id: 239},
  {nombre: "GUAYMARAL", ciudad_id: 240},
  {nombre: "GUSTAVO ARTUNDUAGA PAREDES", ciudad_id: 241},
  {nombre: "HACIENDA GARCIA", ciudad_id: 242},
  {nombre: "HATO COROZAL", ciudad_id: 243},
  {nombre: "HELICENTRO - BOGOTA", ciudad_id: 244},
  {nombre: "PERALES", ciudad_id: 245},
  {nombre: "IPIALES - SAN LUIS", ciudad_id: 246},
  {nombre: "JORGE ISAACS (ANTES LA MINA)", ciudad_id: 247},
  {nombre: "JUANCHACO", ciudad_id: 248},
  {nombre: "JURADO", ciudad_id: 249},
  {nombre: "LA GAVIOTA - VICHADA", ciudad_id: 250},
  {nombre: "LA GLORIA", ciudad_id: 251},
  {nombre: "LA MACARENA - META", ciudad_id: 252},
  {nombre: "LA PEDRERA", ciudad_id: 253},
  {nombre: "LA PRIMAVERA", ciudad_id: 254},
  {nombre: "LA UNION", ciudad_id: 255},
  {nombre: "LA VEGA", ciudad_id: 256},
  {nombre: "LARANDIA", ciudad_id: 257},
  {nombre: "LAS CRUCES", ciudad_id: 258},
  {nombre: "ALFREDO VASQUEZ COBO", ciudad_id: 259},
  {nombre: "LOS COLONIZADORES", ciudad_id: 260},
  {nombre: "LOS TOROS", ciudad_id: 261},
  {nombre: "MADRID 'AFB'", ciudad_id: 262},
  {nombre: "BARACOA", ciudad_id: 263},
  {nombre: "MAICAO", ciudad_id: 264},
  {nombre: "MALAGA", ciudad_id: 265},
  {nombre: "CASANARE", ciudad_id: 266},
  {nombre: "LA NUBIA", ciudad_id: 267},
  {nombre: "MAPIRIPAN", ciudad_id: 268},
  {nombre: "MARCO FIDEL SUAREZ  'AFB'", ciudad_id: 269},
  {nombre: "MARIQUITA", ciudad_id: 270},
  {nombre: "OLAYA HERRERA", ciudad_id: 271},
  {nombre: "MELGAR \"AFB\"", ciudad_id: 272},
  {nombre: "MERCADERES", ciudad_id: 273},
  {nombre: "MILLAN VARGAS", ciudad_id: 274},
  {nombre: "MIRAFLORES", ciudad_id: 275},
  {nombre: "MIRAFLORES", ciudad_id: 276},
  {nombre: "MITU", ciudad_id: 277},
  {nombre: " SAN BERNARDO", ciudad_id: 278},
  {nombre: "CORDOBA", ciudad_id: 279},
  {nombre: "LOS GARZONES", ciudad_id: 280},
  {nombre: "MORELIA", ciudad_id: 281},
  {nombre: "NECOCLI", ciudad_id: 282},
  {nombre: "BENITO SALAS", ciudad_id: 283},
  {nombre: "REYES MURILLO", ciudad_id: 284},
  {nombre: "AGUAS CLARAS", ciudad_id: 285},
  {nombre: "ORITO", ciudad_id: 286},
  {nombre: "OROCUE", ciudad_id: 287},
  {nombre: "JUAN JOSE RONDON", ciudad_id: 288},
  {nombre: "PALANQUERO", ciudad_id: 299},
  {nombre: "ANTONIO NARIÑO", ciudad_id: 290},
  {nombre: "PAZ DE ARIPORO", ciudad_id: 291},
  {nombre: "MATECAÑAS", ciudad_id: 292},
  {nombre: "CONTADOR", ciudad_id: 293},
  {nombre: "LAS FLORES", ciudad_id: 294},
  {nombre: "GMOLEON VALENCIA", ciudad_id: 295},
  {nombre: "EL EMBRUJO", ciudad_id: 296},
  {nombre: "3 DE MAYO", ciudad_id: 297},
  {nombre: "LA MORELA", ciudad_id: 398},
  {nombre: "PORTETE", ciudad_id: 299},
  {nombre: "PUERTO GAITAN", ciudad_id: 300},
  {nombre: "CESAR GAVIRIA", ciudad_id: 301},
  {nombre: "PUERTO LEGUIZAMO", ciudad_id: 302},
  {nombre: "PUERTO LLERAS", ciudad_id: 303},
  {nombre: "PUERTO LOPEZ", ciudad_id: 304},
  {nombre: "PUERTO NARE", ciudad_id: 305},
  {nombre: "EL CARAÑO", ciudad_id: 306},
  {nombre: "REMEDIOS OTU", ciudad_id: 307},
  {nombre: "ALMIRANTE PADILLA", ciudad_id: 308},
  {nombre: "JOSE MARIA CORDOVA", ciudad_id: 309},
  {nombre: "RONDON", ciudad_id: 310},
  {nombre: "SAN AGUSTIN - CA.", ciudad_id: 311},
  {nombre: "GUSTAVO ROJAS PINILLA", ciudad_id: 312},
  {nombre: "LOS POZOS", ciudad_id: 313},
  {nombre: "SAN ISIDRO II", ciudad_id: 314},
  {nombre: "SAN JOSE DEL GUAVIARE", ciudad_id: 315},
  {nombre: "SAN VICENTE DEL CAGUAN", ciudad_id: 316},
  {nombre: "SANTA ANA - VALLE", ciudad_id: 317},
  {nombre: "SIMON BOLIVAR", ciudad_id: 318},
  {nombre: "SANTA ROSA DEL SUR", ciudad_id: 319},
  {nombre: "SANTA ROSALIA", ciudad_id: 320},
  {nombre: "SANTAFE DE ANTIOQUIA", ciudad_id: 321},
  {nombre: "SANTIAGO No.1", ciudad_id: 322},
  {nombre: "SARDINAS", ciudad_id: 323},
  {nombre: "SOGAMOSO - ALBERTO LLERAS C.", ciudad_id: 324},
  {nombre: "TAME", ciudad_id: 325},
  {nombre: "TAPURUCUARA", ciudad_id: 326},
  {nombre: "TARAIRA", ciudad_id: 327},
  {nombre: "TARAPACA", ciudad_id: 328},
  {nombre: "TAURAMENA", ciudad_id: 329},
  {nombre: "TIBU", ciudad_id: 330},
  {nombre: "TIMBIQUI", ciudad_id: 331},
  {nombre: "TIQUIE", ciudad_id: 332},
  {nombre: "TOLEMAIDA \"AFB\"", ciudad_id: 333},
  {nombre: "TOLU", ciudad_id: 334},
  {nombre: "TRES ESQUINAS AB", ciudad_id: 335},
  {nombre: "TRINIDAD", ciudad_id: 336},
  {nombre: "FARFAN HERIBERTO GIL M", ciudad_id: 337},
  {nombre: "LA FLORIDA", ciudad_id: 338},
  {nombre: "TUNJA", ciudad_id: 339},
  {nombre: "GONZALO MEJIA", ciudad_id: 340},
  {nombre: "URIBE", ciudad_id: 341},
  {nombre: "URRAO", ciudad_id: 342},
  {nombre: "ALFONSO LOPEZ P.", ciudad_id: 343},
  {nombre: "VANGUARDIA", ciudad_id: 344},
  {nombre: "VELASQUEZ", ciudad_id: 345},
  {nombre: "VIGIA DEL FUERTE", ciudad_id: 346},
  {nombre: "VILLA GARZON", ciudad_id: 347},
  {nombre: "VILLANUEVA", ciudad_id: 348},
  {nombre: "WACARICUARA", ciudad_id: 349},
  {nombre: "YAGUARA II", ciudad_id: 350},
  {nombre: "YAPU", ciudad_id: 351},
  {nombre: "AGUACHICA - CESAR", ciudad_id: 352},
  {nombre: "EL PASO", ciudad_id: 353},
  {nombre: "EL PORVENIR", ciudad_id: 354},
  {nombre: "INT-SAN FELIX", ciudad_id: 355},
  {nombre: "MARANDUA \"AFB\"", ciudad_id: 356},
  {nombre: "SANTAGUEDA", ciudad_id: 357},
  {nombre: "ABIDJAN", ciudad_id: 358},
  {nombre: "DANIEL ODUBER QUIROS INTL", ciudad_id: 359},
  {nombre: "GOLFITO", ciudad_id: 360},
  {nombre: "JUAN SANTAMARIA INTL", ciudad_id: 361},
  {nombre: "LIMON INTERNATIONAL", ciudad_id: 362},
  {nombre: "TOBIAS BOLANOS INTL", ciudad_id: 363},
  {nombre: "DUBROVNIK", ciudad_id: 364},
  {nombre: "ANTONIO MACEO", ciudad_id: 365},
  {nombre: "CIEGO DE AVILA", ciudad_id: 366},
  {nombre: "CIENFUEGOS", ciudad_id: 367},
  {nombre: "CUNAGUA", ciudad_id: 368},
  {nombre: "GUANTANAMO BAY NS", ciudad_id: 369},
  {nombre: "HOLGUIN", ciudad_id: 370},
  {nombre: "IGNACIO AGRAMONTE", ciudad_id: 371},
  {nombre: "JOSE MARTI INTL", ciudad_id: 372},
  {nombre: "JUAN GUALBERTO GOMEZ", ciudad_id: 373},
  {nombre: "MANZANILLO", ciudad_id: 374},
  {nombre: "MARIANA GRAJALES", ciudad_id: 375},
  {nombre: "MILITAR", ciudad_id: 376},
  {nombre: "NIL", ciudad_id: 377},
  {nombre: "NIL", ciudad_id: 378},
  {nombre: "PINAR DEL RIO", ciudad_id: 379},
  {nombre: "SANTA CLARA", ciudad_id: 380},
  {nombre: "VILO ACUNA INTL", ciudad_id: 381},
  {nombre: "BILLUND", ciudad_id: 382},
  {nombre: "KASTRUP", ciudad_id: 383},
  {nombre: "CHONGO", ciudad_id: 384},
  {nombre: "COTOPAXI INTL", ciudad_id: 385},
  {nombre: "EL COCA", ciudad_id: 386},
  {nombre: "ELOY ALFARO INTL", ciudad_id: 387},
  {nombre: "GENERAL RIVADENEIRA", ciudad_id: 388},
  {nombre: "LAGO AGRIO", ciudad_id: 389},
  {nombre: "MARISCAL SUCRE INTL", ciudad_id: 390},
  {nombre: "SALINAS", ciudad_id: 391},
  {nombre: "SANTA ROSA", ciudad_id: 392},
  {nombre: "SEYMOUR", ciudad_id: 393},
  {nombre: "SIMON BOLIVAR", ciudad_id: 394},
  {nombre: "TAURA", ciudad_id: 395},
  {nombre: "TULCAN", ciudad_id: 396},
  {nombre: "EL SALVADOR INTL", ciudad_id: 397},
  {nombre: "ILOPANGO INTL", ciudad_id: 398},
  {nombre: "ABU DHABI", ciudad_id: 399},
  {nombre: "INTERNATIONAL DUBAI", ciudad_id: 400},
  {nombre: "ALICANTE", ciudad_id: 401},
  {nombre: "BARAJAS", ciudad_id: 402},
  {nombre: "BARCELONA", ciudad_id: 403},
  {nombre: "BILBAO", ciudad_id: 404},
  {nombre: "FUERTEVENTURA", ciudad_id: 405},
  {nombre: "GRANADA", ciudad_id: 406},
  {nombre: "IBIZA", ciudad_id: 407},
  {nombre: "JEREZ", ciudad_id: 408},
  {nombre: "LA CORUÑA", ciudad_id: 409},
  {nombre: "LABACOLLA", ciudad_id: 410},
  {nombre: "LANZAROTE", ciudad_id: 411},
  {nombre: "MALAGA", ciudad_id: 412},
  {nombre: "NORTE LOS RODEOS", ciudad_id: 413},
  {nombre: "PALMA DE MAYORCA", ciudad_id: 414},
  {nombre: "PAMPLONA NOAIN", ciudad_id: 415},
  {nombre: "REINA SOFIA", ciudad_id: 416},
  {nombre: "SALAMANCA", ciudad_id: 417},
  {nombre: "SAN JAVIER", ciudad_id: 418},
  {nombre: "SAN PABLO", ciudad_id: 419},
  {nombre: "TORREJON DE ARDOZ", ciudad_id: 420},
  {nombre: "VALENCIA", ciudad_id: 421},
  {nombre: "VALLADOLID AIRPORT", ciudad_id: 422},
  {nombre: "VIGO", ciudad_id: 423},
  {nombre: "ZARAGOZA", ciudad_id: 424},
  {nombre: " JOHNSTOWN-CAMBRIA", ciudad_id: 425},
  {nombre: " MERIDIAN/ KEY FIELD", ciudad_id: 426},
  {nombre: " ROSCOE TURNER", ciudad_id: 427},
  {nombre: "ABELINE DYESS", ciudad_id: 428},
  {nombre: "ABERDEEN REGIONAL", ciudad_id: 429},
  {nombre: "ABRAHAM LINCOLN", ciudad_id: 430},
  {nombre: "ADAMS FIELD", ciudad_id: 431},
  {nombre: "ADDISON AIRPORT", ciudad_id: 432},
  {nombre: "AIRBORNE AIRPARK", ciudad_id: 433},
  {nombre: "AIRPORT REGIONAL DE COLUMBIA", ciudad_id: 434},
  {nombre: "AKRON", ciudad_id: 435},
  {nombre: "AKRON- CANTON", ciudad_id: 436},
  {nombre: "ALBANY", ciudad_id: 437},
  {nombre: "ALBANY COUNTRY", ciudad_id: 438},
  {nombre: "ALBUQUERQUE INTL SUNPORT", ciudad_id: 439},
  {nombre: "ALEXANDRIA INTL", ciudad_id: 440},
  {nombre: "ALLEGHENY COUNTRY", ciudad_id: 441},
  {nombre: "ALLIANCE. TX", ciudad_id: 442},
  {nombre: "ALPENA COUNTRY REGIONAL", ciudad_id: 443},
  {nombre: "ALTUS AFB,OK", ciudad_id: 444},
  {nombre: "ALVIN CALLENDER FIELD", ciudad_id: 445},
  {nombre: "AMARILLO INTL", ciudad_id: 446},
  {nombre: "ANDERSON COUNTRY", ciudad_id: 447},
  {nombre: "ANDREWS AFB", ciudad_id: 448},
  {nombre: "ANDREWS AFB", ciudad_id: 449},
  {nombre: "ANNISTON METROPOLITA", ciudad_id: 450},
  {nombre: "ASHEVILLE REGIONAL", ciudad_id: 451},
  {nombre: "ATLANTIC CITY INTL", ciudad_id: 452},
  {nombre: "AUGUSTA", ciudad_id: 453},
  {nombre: "AUGUSTA", ciudad_id: 454},
  {nombre: "AURORA MUNICIPAL", ciudad_id: 455},
  {nombre: "AUSTIN/ROBERT/MUELLER MUNICIPA", ciudad_id: 456},
  {nombre: "AYER MOORE AAF", ciudad_id: 457},
  {nombre: "BALTIMORE WASHINGTON INTERNAL", ciudad_id: 458},
  {nombre: "BANGOR INTL", ciudad_id: 459},
  {nombre: "BARK DALE AFB", ciudad_id: 460},
  {nombre: "BARNES MUNI", ciudad_id: 461},
  {nombre: "BATON ROUGE", ciudad_id: 462},
  {nombre: "BATTLE CREEK INT", ciudad_id: 463},
  {nombre: "BAUDETTE INTL", ciudad_id: 464},
  {nombre: "BEALE AFB", ciudad_id: 465},
  {nombre: "BELLINGHAM INTL", ciudad_id: 466},
  {nombre: "BEN EPPS", ciudad_id: 467},
  {nombre: "BERGSTROM AFB", ciudad_id: 468},
  {nombre: "BERT MOONEY", ciudad_id: 469},
  {nombre: "BETHLEHEM-EASTON", ciudad_id: 470},
  {nombre: "BICYCLE LAKE AAF", ciudad_id: 471},
  {nombre: "BILLINGS LOGAN INTL", ciudad_id: 472},
  {nombre: "BILOXP", ciudad_id: 473},
  {nombre: "BIRMINGHAM INTL", ciudad_id: 474},
  {nombre: "BISMARCK MUNI", ciudad_id: 475},
  {nombre: "BLAIR COUNTRY", ciudad_id: 476},
  {nombre: "BLUE GRASS - LEXINGTON", ciudad_id: 477},
  {nombre: "BOB SIKES", ciudad_id: 478},
  {nombre: "BOCA RATON", ciudad_id: 479},
  {nombre: "BOLLING AFB", ciudad_id: 480},
  {nombre: "BRADFORT REGIONAL", ciudad_id: 481},
  {nombre: "BRADLEY INTL", ciudad_id: 482},
  {nombre: "BROWN FIELD MUNICIPAL", ciudad_id: 483},
  {nombre: "BUCKLEY ANGB", ciudad_id: 484},
  {nombre: "BURBANK", ciudad_id: 485},
  {nombre: "BURKE LAKEFRONT", ciudad_id: 486},
  {nombre: "BURLEY MUNI", ciudad_id: 487},
  {nombre: "BURLINGTON INTL", ciudad_id: 488},
  {nombre: "BURLINGTON MINI", ciudad_id: 489},
  {nombre: "CAMARILLO", ciudad_id: 490},
  {nombre: "CAPE GIRARDEAU", ciudad_id: 491},
  {nombre: "CARIBOU MUNI", ciudad_id: 492},
  {nombre: "CARTERSVILLE", ciudad_id: 493},
  {nombre: "CEDAR CITY", ciudad_id: 494},
  {nombre: "CENTENNIAL AIPORT", ciudad_id: 495},
  {nombre: "CHANDLER FIELD", ciudad_id: 496},
  {nombre: "CHARLES M SCHULZ- SONOMA", ciudad_id: 497},
  {nombre: "CHARLESTON AFB INTL", ciudad_id: 498},
  {nombre: "CHARLOTTE DOUGLAS INTL", ciudad_id: 499},
  {nombre: "CHARLOTTESVILLE-ALBEMARLE", ciudad_id: 500},
  {nombre: "CHERRY POINT MCAS", ciudad_id: 501},
  {nombre: "CHICAGO", ciudad_id: 502},
  {nombre: "CLEVELAND HOPKINS", ciudad_id: 503},
  {nombre: "COCOA BEACH", ciudad_id: 504},
  {nombre: "COLORADO SPRINGS MUNICIPAL", ciudad_id: 505},
  {nombre: "COLUMBUS", ciudad_id: 506},
  {nombre: "COLUMBUS MUNI", ciudad_id: 507},
  {nombre: "CONCORD REGIONAL", ciudad_id: 508},
  {nombre: "CORPUS CHRISTI", ciudad_id: 509},
  {nombre: "CORPUS CHRISTI NAS", ciudad_id: 510},
  {nombre: "COVINGTON - CINCINNATI", ciudad_id: 511},
  {nombre: "CUYAHOGA", ciudad_id: 512},
  {nombre: "DALLAS", ciudad_id: 513},
  {nombre: "DANNELLY FIELD", ciudad_id: 514},
  {nombre: "DAVID WAYNE HOOKS MEMORIAL", ciudad_id: 515},
  {nombre: "DAVIS MONTHAN AIR FORCE", ciudad_id: 516},
  {nombre: "DAYTONA BEACH", ciudad_id: 517},
  {nombre: "DECATUR AIRPORT", ciudad_id: 518},
  {nombre: "DEL CAMPO DE ELLINGTON", ciudad_id: 519},
  {nombre: "DEL CONDADO DE BOEING FIEL", ciudad_id: 520},
  {nombre: "DEL RIO LAUGHLIN /AFB", ciudad_id: 521},
  {nombre: "DENVER JEFFCO", ciudad_id: 522},
  {nombre: "DETROIT WILLOW", ciudad_id: 523},
  {nombre: "DOBBINS", ciudad_id: 524},
  {nombre: "DOTHAN", ciudad_id: 525},
  {nombre: "DOVER AFB", ciudad_id: 526},
  {nombre: "DOWNTOWN", ciudad_id: 527},
  {nombre: "DRAUGHON MILLER CENTRAL", ciudad_id: 528},
  {nombre: "DRESS MEMORIAL", ciudad_id: 529},
  {nombre: "DULLES", ciudad_id: 530},
  {nombre: "DULLES INTL D.C.", ciudad_id: 531},
  {nombre: "DURHAM, NC.", ciudad_id: 532},
  {nombre: "EAGLE COUNTY", ciudad_id: 533},
  {nombre: "EAKER AFB", ciudad_id: 534},
  {nombre: "EDWIN A LINK FIELD", ciudad_id: 535},
  {nombre: "EL MONTE INTER", ciudad_id: 536},
  {nombre: "EL PASO INTERNATIONAL", ciudad_id: 537},
  {nombre: "EL PASO TEXAS", ciudad_id: 538},
  {nombre: "ELIZABETH  CITY COAST  GUARD", ciudad_id: 539},
  {nombre: "EPPLEY AFLD", ciudad_id: 540},
  {nombre: "ESTADOS UNIDOS", ciudad_id: 541},
  {nombre: "EUREKA", ciudad_id: 542},
  {nombre: "EXECUTIVE", ciudad_id: 543},
  {nombre: "EXPRESS", ciudad_id: 544},
  {nombre: "FAA ATC SYSTEMS COMMAND CENTER", ciudad_id: 545},
  {nombre: "FAIRCHILD AFB", ciudad_id: 546},
  {nombre: "FAIRFIEL MUNICIPAL", ciudad_id: 547},
  {nombre: "FAIRFIELD/TRAVIS AFB, CA", ciudad_id: 548},
  {nombre: "FALCOM FIELD", ciudad_id: 549},
  {nombre: "FAYETTEVELLI", ciudad_id: 550},
  {nombre: "FAYETTVILLE INTER", ciudad_id: 551},
  {nombre: "FOR WORTH MEACHAM INTERNATIONA", ciudad_id: 552},
  {nombre: "FOR WORTH NAVAL AIR STATION", ciudad_id: 553},
  {nombre: "FORT LAUDERDALE EXECUTIVE", ciudad_id: 554},
  {nombre: "FORT LAUDERDALE HOLLYWOOD INTL", ciudad_id: 555},
  {nombre: "FORT WAHON BEACH", ciudad_id: 556},
  {nombre: "FORT WAYNE", ciudad_id: 557},
  {nombre: "FORT WORTH", ciudad_id: 558},
  {nombre: "FT WORTH", ciudad_id: 559},
  {nombre: "FULTON/COUNTY-BROWN,GA", ciudad_id: 560},
  {nombre: "GALLATIN", ciudad_id: 561},
  {nombre: "GEN.EDWARD L.LOGAN", ciudad_id: 562},
  {nombre: "GENERAL MITCHELL INTL", ciudad_id: 563},
  {nombre: "GEORGE BUSH INTCNTL HOUSTON", ciudad_id: 564},
  {nombre: "GLYNCO JETPORT", ciudad_id: 565},
  {nombre: "GOLDSBORO/SEYMCUR-JOHNSON  AFB", ciudad_id: 566},
  {nombre: "GOOD YEAR AIRPORT", ciudad_id: 567},
  {nombre: "GOWEN FLD", ciudad_id: 568},
  {nombre: "GRAY ARMY AIR FIELD", ciudad_id: 569},
  {nombre: "GREATER BUFFALO", ciudad_id: 570},
  {nombre: "GREATFALLS INTERNATIONAL", ciudad_id: 571},
  {nombre: "HANOVER COUNTY MUNICIPAL", ciudad_id: 572},
  {nombre: "HARRISBURG", ciudad_id: 573},
  {nombre: "HARTSFIELD JACKSON ATLANTA INT", ciudad_id: 574},
  {nombre: "HENDERSON EXECUTIVE", ciudad_id: 575},
  {nombre: "HERDON", ciudad_id: 576},
  {nombre: "HILTON HEAD INTERNATIONAL", ciudad_id: 577},
  {nombre: "HOLLOMAN  AIR FORCE BASE", ciudad_id: 578},
  {nombre: "HOMESTEAD AFB", ciudad_id: 579},
  {nombre: "HUMMEL FIELD AIRPORT SALUDA", ciudad_id: 580},
  {nombre: "HUNTER AAF", ciudad_id: 581},
  {nombre: "HUNTSVILLE INTL CARL T JONES F", ciudad_id: 582},
  {nombre: "IGOR I SIKORSKI MEMORIAL", ciudad_id: 583},
  {nombre: "INDIANAPOLIS INTERNATIONAL", ciudad_id: 584},
  {nombre: "INTER IETPORT", ciudad_id: 585},
  {nombre: "INTER PITTSBURGH", ciudad_id: 586},
  {nombre: "INTER RICHMOND", ciudad_id: 587},
  {nombre: "INTERNACIONAL", ciudad_id: 588},
  {nombre: "JACK MCNAMARA FIELD", ciudad_id: 589},
  {nombre: "JACKSON", ciudad_id: 590},
  {nombre: "JACKSONVILLE INTERNAL AIRPORT", ciudad_id: 591},
  {nombre: "JACKSONVILLE NAS(TOWERS", ciudad_id: 592},
  {nombre: "JACQUELINE COCHRAN", ciudad_id: 593},
  {nombre: "JAMES COX", ciudad_id: 594},
  {nombre: "JEFFERSON COUNTRY", ciudad_id: 595},
  {nombre: "JOHN F KENNEDY INTL", ciudad_id: 596},
  {nombre: "JOHN F.KENNEDY", ciudad_id: 597},
  {nombre: "JOHN WAYNE", ciudad_id: 598},
  {nombre: "JR ALISON", ciudad_id: 599},
  {nombre: "KEESLER", ciudad_id: 600},
  {nombre: "KELLY", ciudad_id: 601},
  {nombre: "KENDALL TAMIAMI EXECUTIVE", ciudad_id: 602},
  {nombre: "KENT COUNTRY", ciudad_id: 603},
  {nombre: "KEY  WEST NAS (BOCA CHICA FIEL", ciudad_id: 604},
  {nombre: "KEY WEST INTL", ciudad_id: 605},
  {nombre: "KING COUNTRY INTL", ciudad_id: 606},
  {nombre: "KISSMMEE GATEWAY AIRPORT", ciudad_id: 607},
  {nombre: "KODIAK MUNICIPAL AIRPORT", ciudad_id: 608},
  {nombre: "LA GUARDIA", ciudad_id: 609},
  {nombre: "LADERO/INTL", ciudad_id: 610},
  {nombre: "LAFAYETTE REGIONAL AIRPORT", ciudad_id: 611},
  {nombre: "LAKE CITY MUNICIPAL AIRPORT", ciudad_id: 612},
  {nombre: "LANCASTER", ciudad_id: 613},
  {nombre: "LAS VEGAS", ciudad_id: 614},
  {nombre: "LAURENCE G.HANSCOM", ciudad_id: 615},
  {nombre: "LEESBURG", ciudad_id: 616},
  {nombre: "LIBERMAN MUNICIPAL AIRPORT", ciudad_id: 617},
  {nombre: "LINCOLN/MUNICIPAL", ciudad_id: 618},
  {nombre: "LINDBERGH FIELD", ciudad_id: 619},
  {nombre: "LINDER REGIONAL", ciudad_id: 620},
  {nombre: "LONG BEACH", ciudad_id: 621},
  {nombre: "LOS ANGELES INTL", ciudad_id: 622},
  {nombre: "LOUIS VILLE / STANDIFORD", ciudad_id: 623},
  {nombre: "LOVELL", ciudad_id: 624},
  {nombre: "LUNKEN FIELD", ciudad_id: 625},
  {nombre: "MACDILL AFB FL", ciudad_id: 626},
  {nombre: "MANASSAS RGNL HARRY P DAVIS FL", ciudad_id: 627},
  {nombre: "MANCHESTER - NEW HAMPSHIRE", ciudad_id: 628},
  {nombre: "MARATHON FLIGHT STRIP", ciudad_id: 629},
  {nombre: "MC CONNELL AFB", ciudad_id: 630},
  {nombre: "MC GHEE TYSO", ciudad_id: 631},
  {nombre: "MCCHORD AIRFORCE BASE", ciudad_id: 632},
  {nombre: "MCGUIRE AFB", ciudad_id: 633},
  {nombre: "MCLLEN/MILLER INT", ciudad_id: 634},
  {nombre: "MEADOWS FIELD", ciudad_id: 635},
  {nombre: "MEMPHIS INTERNATIONATIONAL", ciudad_id: 636},
  {nombre: "MERRILL C MEIGS", ciudad_id: 637},
  {nombre: "METROPOLITAN", ciudad_id: 638},
  {nombre: "METROPOLITAN", ciudad_id: 639},
  {nombre: "METROPOLITAN INTERNACIONAL", ciudad_id: 640},
  {nombre: "METROPOLITAN OAKLAND KO.", ciudad_id: 641},
  {nombre: "MIAMI INTL", ciudad_id: 642},
  {nombre: "MINNEAPOLIS ST PAUL INTL", ciudad_id: 643},
  {nombre: "MOBILE DOWNTOWN", ciudad_id: 644},
  {nombre: "MOBILEBILE REGIONAL", ciudad_id: 645},
  {nombre: "MOISANT FIED", ciudad_id: 646},
  {nombre: "MONREO CONUTRY", ciudad_id: 647},
  {nombre: "MONROE AIPORT", ciudad_id: 648},
  {nombre: "MONROE COUNTRY", ciudad_id: 649},
  {nombre: "MUNI", ciudad_id: 650},
  {nombre: "MUNI", ciudad_id: 651},
  {nombre: "MUNICIPAL", ciudad_id: 652},
  {nombre: "MUNICIPAL, CA", ciudad_id: 653},
  {nombre: "NANTUCKET MEMORIAL", ciudad_id: 654},
  {nombre: "NAPLES MUNICIPAL", ciudad_id: 655},
  {nombre: "NAS BRUNSWICKS MAINE", ciudad_id: 656},
  {nombre: "NAS JRB DE LA ARBOLEDA DEL SAU", ciudad_id: 657},
  {nombre: "NEW CASTLE,DELAWARE", ciudad_id: 658},
  {nombre: "NEW HAVEN/TWEED", ciudad_id: 659},
  {nombre: "NEW ORLEANS /LAKEFRONT L.A", ciudad_id: 660},
  {nombre: "NEWARK LIBERTY INTL", ciudad_id: 661},
  {nombre: "NEWHANNOVER INTL", ciudad_id: 662},
  {nombre: "NORFOLKVA BEACH", ciudad_id: 663},
  {nombre: "NORMAL", ciudad_id: 664},
  {nombre: "NORTH ISLAND NAS HALSEY", ciudad_id: 665},
  {nombre: "O .HARE", ciudad_id: 666},
  {nombre: "OAHU, HI", ciudad_id: 667},
  {nombre: "OAKLAND COUNTY INTL", ciudad_id: 668},
  {nombre: "ONTARIO INTERNATIONAL", ciudad_id: 669},
  {nombre: "OPA LOCKA", ciudad_id: 670},
  {nombre: "ORLANDO INTERNATIONAL", ciudad_id: 671},
  {nombre: "ORLANDO/CENTRAL REGIONAL", ciudad_id: 672},
  {nombre: "PALM BEACH INTL", ciudad_id: 673},
  {nombre: "PALM SPRINGS INTERNATIO BUREAU", ciudad_id: 674},
  {nombre: "PAL-WAUKKEE", ciudad_id: 675},
  {nombre: "PARIS", ciudad_id: 676},
  {nombre: "PATTERSON AIR FORCE", ciudad_id: 677},
  {nombre: "PATUXENT RIVER NAVAL AIR STATI", ciudad_id: 678},
  {nombre: "PEACHTREE", ciudad_id: 679},
  {nombre: "PENNSYLVANIA", ciudad_id: 680},
  {nombre: "PENSACALA REGIONAL", ciudad_id: 681},
  {nombre: "PHILADELPHIA INTL, PA.", ciudad_id: 682},
  {nombre: "PHILLIPS AAF PROVING GROUND", ciudad_id: 683},
  {nombre: "PIEDMONT TRIAD INTL", ciudad_id: 684},
  {nombre: "PINAL AIRPARK", ciudad_id: 685},
  {nombre: "POEL ARMY AIRFIELD", ciudad_id: 686},
  {nombre: "POPE AFB,NC", ciudad_id: 687},
  {nombre: "POPLAR BLUFF MUNI", ciudad_id: 688},
  {nombre: "PORT COLUMBUS INTERNATIONAL", ciudad_id: 689},
  {nombre: "PORTLAND - HILLSBORO", ciudad_id: 690},
  {nombre: "PORTLAND INTL", ciudad_id: 691},
  {nombre: "PORTSMOUNTH INTERNATIONAL", ciudad_id: 692},
  {nombre: "PUNTA GORDA", ciudad_id: 693},
  {nombre: "QUAD CITY", ciudad_id: 694},
  {nombre: "QUANTICO MARINE CORPS AIRFIELD", ciudad_id: 695},
  {nombre: "RALEIGH COUNTRY MEMORIAL", ciudad_id: 696},
  {nombre: "REGIONAL", ciudad_id: 697},
  {nombre: "RENO INTER", ciudad_id: 698},
  {nombre: "REPUBLIC AIRPORT", ciudad_id: 699},
  {nombre: "REVERSIDE", ciudad_id: 700},
  {nombre: "RICKENBACKER INTL", ciudad_id: 701},
  {nombre: "ROANOKE MUNICIPAL", ciudad_id: 702},
  {nombre: "ROBERT GRAY ARMY AIRFIELD", ciudad_id: 703},
  {nombre: "ROCHESTER INTL", ciudad_id: 704},
  {nombre: "ROGERS MUNI CARTER FLD", ciudad_id: 705},
  {nombre: "ROSECRANS MEMORIAL", ciudad_id: 706},
  {nombre: "ROSEWELL INDUSTRIAL AIR CENTER", ciudad_id: 707},
  {nombre: "SACRAMENTO", ciudad_id: 708},
  {nombre: "SALT LAKE CITY INTL", ciudad_id: 709},
  {nombre: "SAN ANTONIO / INTL, TX.", ciudad_id: 710},
  {nombre: "SAN FRANCISCO / INTL, CA.", ciudad_id: 711},
  {nombre: "SAN JOSE INTERNATIONAL", ciudad_id: 712},
  {nombre: "SARASOTA BRADENTON", ciudad_id: 713},
  {nombre: "SARDY FIELD", ciudad_id: 714},
  {nombre: "SCHENECTADY  COUNTY", ciudad_id: 715},
  {nombre: "SCOTT", ciudad_id: 716},
  {nombre: "SCOTTSDALE", ciudad_id: 717},
  {nombre: "SEATTLE", ciudad_id: 718},
  {nombre: "SELFRIDGE AIR NATIONAL GUARD B", ciudad_id: 719},
  {nombre: "SHREPORT REGIONAL", ciudad_id: 720},
  {nombre: "SIN ACTUALIZAR", ciudad_id: 721},
  {nombre: "SKY HARBORT INTERNATIONAL", ciudad_id: 722},
  {nombre: "SMYRNA APRT,TN", ciudad_id: 723},
  {nombre: "SOUTH PADRE IS.INTERNATIONAL.T", ciudad_id: 724},
  {nombre: "SOUTHWEST", ciudad_id: 725},
  {nombre: "SPB", ciudad_id: 726},
  {nombre: "SPIRIT OF SAINT LOUIS", ciudad_id: 727},
  {nombre: "ST LOUIS REGIONAL", ciudad_id: 728},
  {nombre: "ST PAUL DOWNTON AIRPORT", ciudad_id: 729},
  {nombre: "ST. LOUIS", ciudad_id: 730},
  {nombre: "ST.PETERSBURG", ciudad_id: 731},
  {nombre: "STANTON AIRFIELD", ciudad_id: 732},
  {nombre: "STAPLETON  INT", ciudad_id: 733},
  {nombre: "STATESVILLE RGNL", ciudad_id: 734},
  {nombre: "STENNIS INTERNATIONAL", ciudad_id: 735},
  {nombre: "STEWART INTERNATIONAL", ciudad_id: 736},
  {nombre: "SUGAR LAND REGIONAL", ciudad_id: 737},
  {nombre: "SUSSEY", ciudad_id: 738},
  {nombre: "SYRACUSE INTER", ciudad_id: 739},
  {nombre: "TAMPA INTL", ciudad_id: 740},
  {nombre: "TENNESSEE", ciudad_id: 741},
  {nombre: "TETERBORO", ciudad_id: 742},
  {nombre: "THEODORE FRANCIS", ciudad_id: 743},
  {nombre: "THOMASTON UPSON", ciudad_id: 744},
  {nombre: "TINKER AFB", ciudad_id: 745},
  {nombre: "TRENT LOTT INTERNATIONAL", ciudad_id: 746},
  {nombre: "TRENTON  MERCE", ciudad_id: 747},
  {nombre: "TUCSON INTERNATIONAL AIRPORT", ciudad_id: 748},
  {nombre: "TULSA INTERNACIONAL", ciudad_id: 749},
  {nombre: "VALDOSTA REGIONAL", ciudad_id: 750},
  {nombre: "VAN NUYS", ciudad_id: 751},
  {nombre: "VERO BECH MUNICIPAL AIRPORT", ciudad_id: 752},
  {nombre: "VICTORVILLE /  SOUTHERN", ciudad_id: 753},
  {nombre: "W H BUD BARRON  DUBLIN", ciudad_id: 754},
  {nombre: "W K KELLOGG", ciudad_id: 755},
  {nombre: "WACO REGIONAL", ciudad_id: 756},
  {nombre: "WALLA WALLA REGIONAL", ciudad_id: 757},
  {nombre: "WARNER ROBINS GA.", ciudad_id: 758},
  {nombre: "WARREN COUNTRY", ciudad_id: 759},
  {nombre: "WASHINHTON (ARTCC), DC", ciudad_id: 760},
  {nombre: "WATERLOO MUNI", ciudad_id: 761},
  {nombre: "WATERTOWN INTL", ciudad_id: 762},
  {nombre: "WATERTOWN MUNI", ciudad_id: 763},
  {nombre: "WAUKEGAN RGNL", ciudad_id: 764},
  {nombre: "WAUKESHA COUNTY AIRPORT", ciudad_id: 765},
  {nombre: "WAYNE COUNTY", ciudad_id: 766},
  {nombre: "WAYNE MUNICIPAL AIRPORT", ciudad_id: 767},
  {nombre: "WEST BEND MUNI", ciudad_id: 768},
  {nombre: "WESTOVER AFB METROPOLITAN", ciudad_id: 769},
  {nombre: "WHITE PLAINS", ciudad_id: 770},
  {nombre: "WHITE SAND REGIONAL", ciudad_id: 771},
  {nombre: "WICHITA MID CONTINENT", ciudad_id: 772},
  {nombre: "WILEY POST", ciudad_id: 773},
  {nombre: "WILKES BARRE INTL", ciudad_id: 774},
  {nombre: "WILL ROGERS WORLDS", ciudad_id: 775},
  {nombre: "WILLAM P HOBBY TX", ciudad_id: 776},
  {nombre: "WILLIAMBURGS INTERNATIONAL", ciudad_id: 777},
  {nombre: "WISCONSIN", ciudad_id: 778},
  {nombre: "WLKES CO", ciudad_id: 779},
  {nombre: "YUMA MARINE", ciudad_id: 780},
  {nombre: "FRANCIS GABRESKI", ciudad_id: 781},
  {nombre: "MAC ARTHUR", ciudad_id: 782},
  {nombre: "MORRISTOWN/MUNI N.J", ciudad_id: 783},
  {nombre: "NIAGARA FALLS", ciudad_id: 784},
  {nombre: "BISBEE-DOUGLAS INTERNATIONAL A", ciudad_id: 785},
  {nombre: "RANDOLFPH AIRFORCE BASE", ciudad_id: 786},
  {nombre: "SHEBOYGAM COUNTY MEMORIAL", ciudad_id: 787},
  {nombre: "LEESBURG", ciudad_id: 788},
  {nombre: "OCEANA NAVAL AIR STATION", ciudad_id: 789},
  {nombre: "WINCHESTER RNG", ciudad_id: 790},
  {nombre: "NINOY AQUINO", ciudad_id: 791},
  {nombre: "CAPE  CANAVERAL AIR FORCE", ciudad_id: 792},
  {nombre: "CECIL FLD", ciudad_id: 793},
  {nombre: "EGLIN AFB", ciudad_id: 794},
  {nombre: "HERNANDO COUNTY", ciudad_id: 795},
  {nombre: "MELBOURNE", ciudad_id: 796},
  {nombre: "OCALA INTERNATIONAL", ciudad_id: 797},
  {nombre: "SPACE COAST -TITUSVILLE", ciudad_id: 798},
  {nombre: "ST.LUCIE COUNTY", ciudad_id: 799},
  {nombre: "WITHAM FIELD", ciudad_id: 800},
  {nombre: "BLAGNAC", ciudad_id: 801},
  {nombre: "CHARLES DE GAULLE", ciudad_id: 802},
  {nombre: "CORNOUAIL", ciudad_id: 803},
  {nombre: "COTE D'AZUR", ciudad_id: 804},
  {nombre: "LA GARENNE", ciudad_id: 805},
  {nombre: "LE BOURGET", ciudad_id: 806},
  {nombre: "LESQUIN", ciudad_id: 807},
  {nombre: "ORLY", ciudad_id: 808},
  {nombre: "PERIGUEUX", ciudad_id: 809},
  {nombre: "TOUSSUS", ciudad_id: 810},
  {nombre: "LEON M BA", ciudad_id: 811},
  {nombre: "COLUMBUS INTERNATIONAL", ciudad_id: 812},
  {nombre: "GWINNETT COUNTY AIRPORT", ciudad_id: 813},
  {nombre: "LA AURORA", ciudad_id: 814},
  {nombre: "MELCHOR MENCOS", ciudad_id: 815},
  {nombre: "SAN JOSE", ciudad_id: 816},
  {nombre: "TIKAL INTERNATIONAL FLORES", ciudad_id: 817},
  {nombre: "CHEDDIJAGAN INTL", ciudad_id: 818},
  {nombre: "TIMERHI", ciudad_id: 819},
  {nombre: "OGLE AIRPORT", ciudad_id: 820},
  {nombre: "ROCHAMBEAU", ciudad_id: 821},
  {nombre: "CAP HAITIEN", ciudad_id: 822},
  {nombre: "PORT AU PRINCE INTL", ciudad_id: 823},
  {nombre: "SCHIPHOL", ciudad_id: 824},
  {nombre: "ZESTIENHOVEN", ciudad_id: 825},
  {nombre: "CORONEL ENRIQUE SOTO CANO AB", ciudad_id: 826},
  {nombre: "GOLOSON INTL", ciudad_id: 827},
  {nombre: "LA MESA", ciudad_id: 828},
  {nombre: "LA MESA INTL", ciudad_id: 829},
  {nombre: "ROATAN", ciudad_id: 830},
  {nombre: "TONCONTIN", ciudad_id: 831},
  {nombre: "CHEK LAP KOK", ciudad_id: 832},
  {nombre: "FERIHEGY", ciudad_id: 833},
  {nombre: "MUMBAI", ciudad_id: 834},
  {nombre: "BRISTOL  INTERNATIONAL", ciudad_id: 835},
  {nombre: "CYDE", ciudad_id: 836},
  {nombre: "FAIRFORD ROYAL AIR FORCE BASE", ciudad_id: 837},
  {nombre: "FAMBOROUGH HAMPSHIRE", ciudad_id: 838},
  {nombre: "GATWICK", ciudad_id: 839},
  {nombre: "GLASGOW INTERNATIONAL", ciudad_id: 840},
  {nombre: "HEATHROW", ciudad_id: 841},
  {nombre: "INTERNATIONAL BIRMINGHAN", ciudad_id: 842},
  {nombre: "LONDON STANSTED", ciudad_id: 843},
  {nombre: "MANCHESTER/INTL", ciudad_id: 844},
  {nombre: "MANSTON (CIVIL)", ciudad_id: 845},
  {nombre: "SOUTHAMPTON", ciudad_id: 846},
  {nombre: "MEHRABAD", ciudad_id: 847},
  {nombre: "DUBLIN", ciudad_id: 848},
  {nombre: "INTERNATIONAL BELFAST", ciudad_id: 849},
  {nombre: "SHANNON", ciudad_id: 850},
  {nombre: "UNITED KINGDOM", ciudad_id: 851},
  {nombre: "MELVILLE HALL", ciudad_id: 852},
  {nombre: "REYKJAVIK", ciudad_id: 853},
  {nombre: "ANGUILLA WALLBLAKE", ciudad_id: 854},
  {nombre: "BERMUDA INTL", ciudad_id: 855},
  {nombre: "CAIMAN BRAC GERRARD", ciudad_id: 856},
  {nombre: "CANOUAN S.T. VICENT", ciudad_id: 857},
  {nombre: "TERRANCE B LETTSOME", ciudad_id: 858},
  {nombre: "GRAND CAYMAN ( CITY )", ciudad_id: 859},
  {nombre: "OWEN ROBERTS INTL", ciudad_id: 860},
  {nombre: "BEN GURION", ciudad_id: 861},
  {nombre: "FIUMIFINO", ciudad_id: 862},
  {nombre: "GUGLIELMO MARCONI", ciudad_id: 863},
  {nombre: "LINATE", ciudad_id: 864},
  {nombre: "MALPENSA", ciudad_id: 865},
  {nombre: "SESTRI", ciudad_id: 866},
  {nombre: "TESSERA", ciudad_id: 867},
  {nombre: "URBE", ciudad_id: 868},
  {nombre: "BOCCOBEL", ciudad_id: 869},
  {nombre: "KEN JONES", ciudad_id: 870},
  {nombre: "MONTEGO BAY", ciudad_id: 871},
  {nombre: "NEGRIL", ciudad_id: 872},
  {nombre: "NORMAN MANLEY", ciudad_id: 873},
  {nombre: "NORMAN MANLEY INTL", ciudad_id: 874},
  {nombre: "SANGSTER INTL", ciudad_id: 875},
  {nombre: "TINSON PEN", ciudad_id: 876},
  {nombre: "INTER HIROSHIMA", ciudad_id: 877},
  {nombre: "NARITA", ciudad_id: 878},
  {nombre: "SHONAI", ciudad_id: 879},
  {nombre: "QUEEN ALIA", ciudad_id: 880},
  {nombre: "FOBER FIELD", ciudad_id: 881},
  {nombre: "INTERNATIONAL INCHEON", ciudad_id: 882},
  {nombre: "RIGA INTER", ciudad_id: 883},
  {nombre: "INTERNATIONAL", ciudad_id: 884},
  {nombre: "CHENNAULT INTERNATIONAL", ciudad_id: 885},
  {nombre: "HOUMA TERREBONNE", ciudad_id: 886},
  {nombre: "SEPANG", ciudad_id: 887},
  {nombre: "MOHAMMED V", ciudad_id: 888},
  {nombre: "AIME CESAIRE", ciudad_id: 889},
  {nombre: "ABELARDO L. RODRIGUEZ / INTL", ciudad_id: 890},
  {nombre: "ABRAHAM  GONZALEZ INTL", ciudad_id: 891},
  {nombre: "AGUASCALIENTES", ciudad_id: 892},
  {nombre: "CABO SAN LUCAS INTERNATIONAL", ciudad_id: 893},
  {nombre: "CAMPECHE", ciudad_id: 894},
  {nombre: "CANANEA", ciudad_id: 895},
  {nombre: "CANCUN INTL", ciudad_id: 896},
  {nombre: "CD.ACUNA", ciudad_id: 897},
  {nombre: "CELAYA", ciudad_id: 898},
  {nombre: "CHETUMAL INTL", ciudad_id: 899},
  {nombre: "CHICHEN ITZA INTERNATIONAL", ciudad_id: 900},
  {nombre: "CHIHUAHUA INTL", ciudad_id: 901},
  {nombre: "CHILPANCINGO", ciudad_id: 902},
  {nombre: "CIUDAD ACUNA INTL", ciudad_id: 903},
  {nombre: "CIUDAD DEL CARMEN", ciudad_id: 904},
  {nombre: "CIUDAD MANTE", ciudad_id: 905},
  {nombre: "CIUDAD OBREGON", ciudad_id: 906},
  {nombre: "CIUDAD VICTORIA", ciudad_id: 907},
  {nombre: "COLIMA", ciudad_id: 908},
  {nombre: "COZUMEL INTL", ciudad_id: 909},
  {nombre: "CUERNAVACA", ciudad_id: 910},
  {nombre: "CULIACAN", ciudad_id: 911},
  {nombre: "DON MIGUEL HIDALGO Y COSTILLA ", ciudad_id: 912},
  {nombre: "DURANGO", ciudad_id: 913},
  {nombre: "ENSENADA", ciudad_id: 914},
  {nombre: "FRANCISCO JAVIER MINA / INTL", ciudad_id: 915},
  {nombre: "GENERAL JOSE MARIA YANEZ INTL", ciudad_id: 916},
  {nombre: "GENERAL JUAN N ALVAREZ INTL", ciudad_id: 917},
  {nombre: "GENERAL MARIANO ESCOBEDO INTL", ciudad_id: 918},
  {nombre: "GUANAJUATO /INTL", ciudad_id: 919},
  {nombre: "GUERRERO NEGRO", ciudad_id: 920},
  {nombre: "GUSTAVO DIAZ ORDAZ / INTL", ciudad_id: 921},
  {nombre: "HERIBERTO JARA / INTL", ciudad_id: 922},
  {nombre: "HERMOSILLO/ INTL", ciudad_id: 923},
  {nombre: "INTL/AP DEL NORTE", ciudad_id: 924},
  {nombre: "ISLA MUJERES", ciudad_id: 925},
  {nombre: "IZTEPEC", ciudad_id: 926},
  {nombre: "JALAPA", ciudad_id: 927},
  {nombre: "LAZARO CARDENAS", ciudad_id: 928},
  {nombre: "LICENCIADO ADOLFO LOPEZ MATEOS", ciudad_id: 929},
  {nombre: "LICENCIADO BENITO JUAREZ INTL", ciudad_id: 930},
  {nombre: "LORETO / INTL", ciudad_id: 931},
  {nombre: "LOS MOCHIS", ciudad_id: 932},
  {nombre: "LUCIO BLANCO / INTL", ciudad_id: 933},
  {nombre: "MANAUEL CRECENCIO REJON / INTL", ciudad_id: 934},
  {nombre: "MANUEL MARQUEZ DE LEON / INTL", ciudad_id: 935},
  {nombre: "MANZANILLO / INTL", ciudad_id: 936},
  {nombre: "MATAMORROS / INTL", ciudad_id: 937},
  {nombre: "MINATITLAN", ciudad_id: 938},
  {nombre: "MONCLOVA", ciudad_id: 939},
  {nombre: "MORELIA", ciudad_id: 940},
  {nombre: "NAUTLA", ciudad_id: 941},
  {nombre: "NOGALES / INTL", ciudad_id: 942},
  {nombre: "NUEVO CASAS GRANDES", ciudad_id: 943},
  {nombre: "NUEVO LAREDO / INTL", ciudad_id: 944},
  {nombre: "OAXACA", ciudad_id: 945},
  {nombre: "PACHUCA", ciudad_id: 946},
  {nombre: "PIEDRAS NEGRAS / INTL", ciudad_id: 947},
  {nombre: "POZA RICA", ciudad_id: 948},
  {nombre: "PUEBLA", ciudad_id: 949},
  {nombre: "PUERTO ESCONDIDO", ciudad_id: 950},
  {nombre: "PUNTA PENASCO", ciudad_id: 951},
  {nombre: "QUERETARO", ciudad_id: 952},
  {nombre: "RAFAEL BUELNA / INTL", ciudad_id: 953},
  {nombre: "RODOLFO SANCHEZ TABOADA / INTL", ciudad_id: 954},
  {nombre: "SALTILLO", ciudad_id: 955},
  {nombre: "SAN FILIPE", ciudad_id: 956},
  {nombre: "SAN JOSE DEL CABO / INTL", ciudad_id: 957},
  {nombre: "SAN LUIS POTOSI", ciudad_id: 958},
  {nombre: "SANTA LUCIA", ciudad_id: 959},
  {nombre: "TAMUIN", ciudad_id: 960},
  {nombre: "TAPACHULA / INTL", ciudad_id: 961},
  {nombre: "TEHACAN", ciudad_id: 962},
  {nombre: "TEPIC", ciudad_id: 963},
  {nombre: "TEQUESQUITENGO", ciudad_id: 964},
  {nombre: "TLAXCALA", ciudad_id: 965},
  {nombre: "TORREON / INTL", ciudad_id: 966},
  {nombre: "TULANCINGO", ciudad_id: 967},
  {nombre: "TUXPAN", ciudad_id: 968},
  {nombre: "TUXTLA GUTIERREZ", ciudad_id: 969},
  {nombre: "TUXTLA GUTIERREZ ( MIL )", ciudad_id: 970},
  {nombre: "URUAPAN", ciudad_id: 971},
  {nombre: "VILLAHERMOSA", ciudad_id: 972},
  {nombre: "XOXOCOTHAN", ciudad_id: 973},
  {nombre: "ZACATECAS", ciudad_id: 974},
  {nombre: "ZAMORA", ciudad_id: 975},
  {nombre: "ZIHUATANEJO / INTL", ciudad_id: 976},
  {nombre: "TUPELO MUNI-CD LEMONS", ciudad_id: 977},
  {nombre: "BLUEFIELDS", ciudad_id: 978},
  {nombre: "BONANZA", ciudad_id: 979},
  {nombre: "MANAGUA INTL", ciudad_id: 980},
  {nombre: "PUERTO CABEZAS", ciudad_id: 981},
  {nombre: "ABUJA NNAMDI AZIKIWE INTL", ciudad_id: 982},
  {nombre: "MAKURDI", ciudad_id: 983},
  {nombre: "GARDERMOEN", ciudad_id: 984},
  {nombre: "SOLA", ciudad_id: 985},
  {nombre: "AUCKLAND", ciudad_id: 986},
  {nombre: "RUZYNE", ciudad_id: 987},
  {nombre: "(AEPTO MILITAR)", ciudad_id: 988},
  {nombre: "AEROPUERTO INTL SCARLET MARTIN", ciudad_id: 989},
  {nombre: "BILBOA ALBROOK AFS", ciudad_id: 990},
  {nombre: "BOCAS DEL TORO", ciudad_id: 991},
  {nombre: "CAP MANUEL NINO INTL", ciudad_id: 992},
  {nombre: "ENRIQUE ADOLFO JIMENEZ", ciudad_id: 993},
  {nombre: "ENRIQUE MALEK", ciudad_id: 994},
  {nombre: "MARCOS A GELABERT INTL", ciudad_id: 995},
  {nombre: "PANAMA PACIFICO (HOWARD) INTER", ciudad_id: 996},
  {nombre: "TOCUMEN INTL", ciudad_id: 997},
  {nombre: "GUARANI", ciudad_id: 998},
  {nombre: "SILVIO PETTIROSSI INTL", ciudad_id: 999},
  {nombre: "ARNOLD PALMER", ciudad_id: 1000},
  {nombre: "PENNRIDGE AIRPORT", ciudad_id: 1001},
  {nombre: "AERP INTER INCA MANCO CAPAS", ciudad_id: 1002},
  {nombre: "CABALLOCOCHA", ciudad_id: 1003},
  {nombre: "CAP FAP GUILLERMO CONCHA", ciudad_id: 1004},
  {nombre: "CAPITAN MONTES", ciudad_id: 1005},
  {nombre: "CORONEL FAP FRANCISCO SECADA V", ciudad_id: 1006},
  {nombre: "EL ESTRECHO", ciudad_id: 1007},
  {nombre: "FAP CARLOS CIRIANI SANTA ROSA", ciudad_id: 1008},
  {nombre: "JOSE ABELARDO QUINON", ciudad_id: 1009},
  {nombre: "LAS PALMAS", ciudad_id: 1010},
  {nombre: "OLMOS", ciudad_id: 1011},
  {nombre: "PEDRO CANGA", ciudad_id: 1012},
  {nombre: "PISCO PERU", ciudad_id: 1013},
  {nombre: "PIURA", ciudad_id: 1014},
  {nombre: "PUCALPA", ciudad_id: 1015},
  {nombre: "PUERTO MALDONADO", ciudad_id: 1016},
  {nombre: "RODRIGUEZ BALLON", ciudad_id: 1017},
  {nombre: "SANTA ROSA", ciudad_id: 1018},
  {nombre: "TARAPOTO", ciudad_id: 1019},
  {nombre: "TRUJILLO/CAPITAN CARLOS MARTIN", ciudad_id: 1020},
  {nombre: "VELAZCO ASTETE", ciudad_id: 1021},
  {nombre: "TENIENTE FAP - CHIMBOTE", ciudad_id: 1022},
  {nombre: "FEDERIC CHOPN", ciudad_id: 1023},
  {nombre: "CASCAIS", ciudad_id: 1024},
  {nombre: "FARO", ciudad_id: 1025},
  {nombre: "FLORES ISLAND AZORE", ciudad_id: 1026},
  {nombre: "LAJES", ciudad_id: 1027},
  {nombre: "LISBOA", ciudad_id: 1028},
  {nombre: "PONTA  DELGADA", ciudad_id: 1029},
  {nombre: "PORTO", ciudad_id: 1030},
  {nombre: "SANTA MARIA", ciudad_id: 1031},
  {nombre: "LUIS MUNOZ MARIN INTL", ciudad_id: 1032},
  {nombre: "MERCEDITA", ciudad_id: 1033},
  {nombre: "ROOSEVELT ROADS", ciudad_id: 1034},
  {nombre: "DOHA", ciudad_id: 1035},
  {nombre: "ARROYO BARRIL", ciudad_id: 1036},
  {nombre: "CIBAO", ciudad_id: 1037},
  {nombre: "HERRERA", ciudad_id: 1038},
  {nombre: "LA ROMANA", ciudad_id: 1039},
  {nombre: "LAS AMERICAS", ciudad_id: 1040},
  {nombre: "PUERTO PLATA", ciudad_id: 1041},
  {nombre: "PUNTA CANA INTL", ciudad_id: 1042},
  {nombre: "SAMANA EL CATEY", ciudad_id: 1043},
  {nombre: "SAN CRISTOBAL LOS MONTONES", ciudad_id: 1044},
  {nombre: "SAN ISIDRO  AB  AIRFORCE BASE", ciudad_id: 1045},
  {nombre: "INTERNATIONAL", ciudad_id: 1046},
  {nombre: "DOMODEDOVO", ciudad_id: 1047},
  {nombre: "SHEREMETYEVO", ciudad_id: 1048},
  {nombre: "GOLDEN ROCK", ciudad_id: 1049},
  {nombre: "DAKAR", ciudad_id: 1050},
  {nombre: "SINGAPORE CHANGI INTL", ciudad_id: 1051},
  {nombre: "ARLAND", ciudad_id: 1052},
  {nombre: "EUROAIRPORT", ciudad_id: 1053},
  {nombre: "SWITZERLAND", ciudad_id: 1054},
  {nombre: "INTER JOHANNESBURG", ciudad_id: 1055},
  {nombre: "CAYANA", ciudad_id: 1056},
  {nombre: "JOHAN ADOLFO PENGEL INTL AIRPO", ciudad_id: 1057},
  {nombre: "PARAMARIBO", ciudad_id: 1058},
  {nombre: "ZORG", ciudad_id: 1059},
  {nombre: "CHIANG KAI SHEK", ciudad_id: 1060},
  {nombre: "RIBERALTA", ciudad_id: 1061},
  {nombre: "PIARCO", ciudad_id: 1062},
  {nombre: "ETIMESGUT", ciudad_id: 1063},
  {nombre: "CARLOS A CURBELO LAGUNA DEL SA", ciudad_id: 1064},
  {nombre: "CARRASCO", ciudad_id: 1065},
  {nombre: "SANTA BENARDINA INTL", ciudad_id: 1066},
  {nombre: "TYDEO LARRE BORGES", ciudad_id: 1067},
  {nombre: "ALBERTO CARNEVALLI", ciudad_id: 1068},
  {nombre: "ANTIGUA  LEEWARDS ", ciudad_id: 1069},
  {nombre: "ARTURO MICHELENA INTL", ciudad_id: 1070},
  {nombre: "GENERAL JOSE ANTON", ciudad_id: 1071},
  {nombre: "BARINAS", ciudad_id: 1072},
  {nombre: "BARQUISIMETO INTL", ciudad_id: 1073},
  {nombre: "CASIQUE ARAMARE", ciudad_id: 1074},
  {nombre: "DEL CARIBE INTL GEN SANTAGO MA", ciudad_id: 1075},
  {nombre: "EL LIBERTADOR", ciudad_id: 1076},
  {nombre: "GENERALISIMO FRANCISCO DE MIRA", ciudad_id: 1077},
  {nombre: "GUAYANA/PUERTO ORDAZ", ciudad_id: 1078},
  {nombre: "ICABARU", ciudad_id: 1079},
  {nombre: "JOSE LEONARDO CH.", ciudad_id: 1080},
  {nombre: "JOSEFA", ciudad_id: 1081},
  {nombre: "JUAN PABLO PEREZ ALFONSO", ciudad_id: 1082},
  {nombre: "KAVANAYEN", ciudad_id: 1083},
  {nombre: "LA CHINITA INTL", ciudad_id: 1084},
  {nombre: "LA FRIA", ciudad_id: 1085},
  {nombre: "MATURIN,MONAGAS", ciudad_id: 1086},
  {nombre: "MAYOR BUENAVENTURA VIVAS", ciudad_id: 1087},
  {nombre: "OSCAR MACHADO ZULOAGA", ciudad_id: 1088},
  {nombre: "SAN ANTONIO DEL TACHIRA", ciudad_id: 1089},
  {nombre: "SIMON BOLIVAR INTL", ciudad_id: 1090},
  {nombre: "LEESBURG", ciudad_id: 1091},
  {nombre: "OCEANA NAVAL AIR STATION", ciudad_id: 1092},
  {nombre: "WINCHESTER RNG", ciudad_id: 1093},
  {nombre: "DESCONOCIDO O NO APLICA ", ciudad_id: 1094}
])
])