
Ciudad.create!([
  { nombre: "MALAGA", pais_codigo: "CO" },
  { nombre: "OCAÑA", pais_codigo: "CO" },
  { nombre: "SOGAMOSO", pais_codigo: "CO" },
  { nombre: "ACANDI", pais_codigo: "CO" },
  { nombre: "VALLEDUPAR", pais_codigo: "CO" },
  { nombre: "PASTO", pais_codigo: "CO" },
  { nombre: "APARTADO", pais_codigo: "CO" },
  { nombre: "MAGANGUE", pais_codigo: "CO" },
  { nombre: "NEIVA", pais_codigo: "CO" },
  { nombre: "PUERTO LEGUIZAMO", pais_codigo: "CO" },
  { nombre: "PUERTO INIRIDA", pais_codigo: "CO" },
  { nombre: "PITALITO", pais_codigo: "CO" },
  { nombre: "CRAVO NORTE", pais_codigo: "CO" },
  { nombre: "CUMARIBO", pais_codigo: "CO" },
  { nombre: "ARARACUARA", pais_codigo: "CO" },
  { nombre: "CAPURGANA", pais_codigo: "CO" },
  { nombre: "JUANCHACO", pais_codigo: "CO" },
  { nombre: "LA CHORRERA", pais_codigo: "CO" },
  { nombre: "LA MACARENA", pais_codigo: "CO" },
  { nombre: "MANIZALES", pais_codigo: "CO" },
  { nombre: "NECOCLI", pais_codigo: "CO" },
  { nombre: "REMEDIO", pais_codigo: "CO" },
  { nombre: "PIZARRO", pais_codigo: "CO" },
  { nombre: "PUERTO RICO", pais_codigo: "CO" },
  { nombre: "TIMBIQUI", pais_codigo: "CO" },
  { nombre: "VILLA GARZON", pais_codigo: "CO" },
  { nombre: "SAN VICENTE DEL CAGUAN", pais_codigo: "CO" },
  { nombre: "YOPAL", pais_codigo: "CO" },
  { nombre: "QUIBDO", pais_codigo: "CO" },
  { nombre: "PROVIDENCIA", pais_codigo: "CO" },
  { nombre: "MONTELIBANO", pais_codigo: "CO" },
  { nombre: "EL BAGRE", pais_codigo: "CO" },
  { nombre: "PUERTO TRIUNFO", pais_codigo: "CO" },
  { nombre: "MITU", pais_codigo: "CO" },
  { nombre: "TAME", pais_codigo: "CO" },
  { nombre: "BUENAVENTURA", pais_codigo: "CO" },
  { nombre: "PUERTO CARREÑO", pais_codigo: "CO" },
  { nombre: "TOLU", pais_codigo: "CO" },
  { nombre: "TURBO", pais_codigo: "CO" },
  { nombre: "CHIA", pais_codigo: "CO" },
  { nombre: "FRONTINO", pais_codigo: "CO" },
  { nombre: "POPAYAN", pais_codigo: "CO" },
  { nombre: "FLORENCIA", pais_codigo: "CO" },
  { nombre: "TUNJA", pais_codigo: "CO" },
  { nombre: "TULUA", pais_codigo: "CO" },
  { nombre: "CALI/ PALMIRA", pais_codigo: "CO" },
  { nombre: "LETICIA", pais_codigo: "CO" },
  { nombre: "RIOHACHA", pais_codigo: "CO" },
  { nombre: "CUCUTA", pais_codigo: "CO" },
  { nombre: "PALESTINA", pais_codigo: "CO" },
  { nombre: "BOGOTA D.C.", pais_codigo: "CO" },
  { nombre: "ARMENIA", pais_codigo: "CO" },
  { nombre: "SOLEDAD ATLANTICA", pais_codigo: "CO" },
  { nombre: "SAN ANDRES", pais_codigo: "CO" },
  { nombre: "MEDELLIN", pais_codigo: "CO" },
  { nombre: "PEREIRA", pais_codigo: "CO" },
  { nombre: "BUCARAMANGA", pais_codigo: "CO" },
  { nombre: "CARTAGENA", pais_codigo: "CO" },
  { nombre: "SANTA MARTA", pais_codigo: "CO" },
  { nombre: "CHIGORONDO", pais_codigo: "CO" },
  { nombre: "SAN JOSE DEL GUAVIARE", pais_codigo: "CO" },
  { nombre: "MAICAO", pais_codigo: "CO" },
  { nombre: "BAHIA SOLANO", pais_codigo: "CO" },
  { nombre: "GUAPU", pais_codigo: "CO" },
  { nombre: "CAUCASIA", pais_codigo: "CO" },
  { nombre: "PAIPA", pais_codigo: "CO" },
  { nombre: "SANTANDER DE QUILICHAO", pais_codigo: "CO" },
  { nombre: "TUMACO", pais_codigo: "CO" },
  { nombre: "SINCELEJO", pais_codigo: "CO" },
  { nombre: "SARAVENA", pais_codigo: "CO" },
  { nombre: "MONTERIA", pais_codigo: "CO" },
  { nombre: "SAN GIL", pais_codigo: "CO" },
  { nombre: "CONDOTO", pais_codigo: "CO" },
  { nombre: "MARIQUITA", pais_codigo: "CO" },
  { nombre: "PUERTO GAITAN", pais_codigo: "CO" },
  { nombre: "IBAGUE", pais_codigo: "CO" },
  { nombre: "PUERTO BOLIVAR", pais_codigo: "CO" },
  { nombre: "NUQUI", pais_codigo: "CO" },
  { nombre: "IPIALES", pais_codigo: "CO" },
  { nombre: "SAN PEDRO DE URABA", pais_codigo: "CO" },
  { nombre: "CARTAGO", pais_codigo: "CO" },
  { nombre: "ARAUCA", pais_codigo: "CO" },
  { nombre: "FLANDES", pais_codigo: "CO" },
  { nombre: "PUERTO ASIS", pais_codigo: "CO" },
  { nombre: "VILLAVICENCIO", pais_codigo: "CO" },
  { nombre: "BARRANCABERMEJA", pais_codigo: "CO" },
  { nombre: "MADRID", pais_codigo: "CO" },
  { nombre: "MARANDU", pais_codigo: "CO" },
  { nombre: "MELGAR", pais_codigo: "CO" },
  { nombre: "SOLANO", pais_codigo: "CO" },
  { nombre: "PUERTO SALGAR", pais_codigo: "CO" },
  { nombre: "SANTIAGO DE CALI", pais_codigo: "CO" },
])