# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ nombre: 'Chicago' }, { nombre: 'Copenhagen' }])
#   Mayor.create(nombre: 'Emanuel', city: cities.first)



Eps.create!([
  { nombre: "Cafesalud" },
  { nombre: "Calisalud" },
  { nombre: "Caprecom" },
  { nombre: "Capresoca" },
  { nombre: "Colmédica" },
  { nombre: "Compensar" },
  { nombre: "Comfenalco Antioquia" },
  { nombre: "Comfenalco Valle" },
  { nombre: "Convida ARS" },
  { nombre: "Coomeva EPS" },
  { nombre: "Cruz Blanca" },
  { nombre: "Famisanar" },
  { nombre: "Humana Vivir" },
  { nombre: "Instituto de los Seguros Sociales" },
  { nombre: "Salud Colmena" },
  { nombre: "Salud Colpatria" },
  { nombre: "Salud Total" },
  { nombre: "Saludcolombia EPS S.A." },
  { nombre: "SaludCoop" },
  { nombre: "Saludvida" },
  { nombre: "Sanitas" },
  { nombre: "Selvasalud" },
  { nombre: "Solsalud" },
  { nombre: "S.O.S EPS" },
  { nombre: "Susalud" }

])

Arl.create!([
  { nombre: "Seguros De Vida Colpatria S.A." },
  { nombre: "Cia. De Seguros Bolivar S.A." },
  { nombre: "Compañia De Seguros De Vida Aurora" },
  { nombre: "Seguros De Vida Alfa S.A." },
  { nombre: "Liberty Seguros De Vida" },
  { nombre: "Arp - Positiva Compañia De Seguros" },
  { nombre: "Riesgos Profesionales Colmena S.A Compañia De Seguros De Vida Arl- Sura" },
  { nombre: "La Equidad Seguros De Vida Organismo Cooperativo - La Equidad Vida" },
  { nombre: "Mapfre Colombia Vida Seguros S.A. " },
  { nombre: "La Previsora Vida S.A. Compañia De Seguros (Iss)" }
])

Rol.create!([
  { nombre: "Administrador", descripcion: "Acceso Total" },
  { nombre: "Medico", descripcion: "Acceso Parcial" },
  { nombre: "Auxiliar", descripcion: "Acceso Limitado" }
])

Ciudad.create!([
  { nombre: "Aguachica", pais_codigo: "CO" },
  { nombre: "Apartadó", pais_codigo: "CO" },
  { nombre: "Arauca", pais_codigo: "CO" },
  { nombre: "Armenia", pais_codigo: "CO" },
  { nombre: "Barrancabermeja", pais_codigo: "CO" },
  { nombre: "Barranquilla", pais_codigo: "CO" },
  { nombre: "Bello", pais_codigo: "CO" },
  { nombre: "Bogotá", pais_codigo: "CO" },
  { nombre: "Bucaramanga", pais_codigo: "CO" },
  { nombre: "Buenaventura", pais_codigo: "CO" },
  { nombre: "Buga", pais_codigo: "CO" },
  { nombre: "Cali", pais_codigo: "CO" },
  { nombre: "Cartago", pais_codigo: "CO" },
  { nombre: "Cartagena", pais_codigo: "CO" },
  { nombre: "Caucasia", pais_codigo: "CO" },
  { nombre: "Chia", pais_codigo: "CO" },
  { nombre: "Ciénaga", pais_codigo: "CO" },
  { nombre: "Cúcuta", pais_codigo: "CO" },
  { nombre: "Dosquebradas", pais_codigo: "CO" },
  { nombre: "Envigado", pais_codigo: "CO" },
  { nombre: "Facatativá", pais_codigo: "CO" },
  { nombre: "Florencia", pais_codigo: "CO" },
  { nombre: "Floridablanca", pais_codigo: "CO" },
  { nombre: "Fusagasugá", pais_codigo: "CO" },
  { nombre: "Girardot", pais_codigo: "CO" },
  { nombre: "Girón", pais_codigo: "CO" },
  { nombre: "Ibagué", pais_codigo: "CO" },
  { nombre: "Itagüí", pais_codigo: "CO" },
  { nombre: "Jamundí", pais_codigo: "CO" },
  { nombre: "Lorica", pais_codigo: "CO" },
  { nombre: "Los Patios", pais_codigo: "CO" },
  { nombre: "Magangué", pais_codigo: "CO" },
  { nombre: "Maicao", pais_codigo: "CO" },
  { nombre: "Malambo", pais_codigo: "CO" },
  { nombre: "Manizales", pais_codigo: "CO" },
  { nombre: "Medellín", pais_codigo: "CO" },
  { nombre: "Melgar", pais_codigo: "CO" },
  { nombre: "Montería", pais_codigo: "CO" },
  { nombre: "Neiva", pais_codigo: "CO" },
  { nombre: "Ocaña", pais_codigo: "CO" },
  { nombre: "Paipa", pais_codigo: "CO" },
  { nombre: "Palmira", pais_codigo: "CO" },
  { nombre: "Pamplona", pais_codigo: "CO" },
  { nombre: "Pereira", pais_codigo: "CO" },
  { nombre: "Piedecuesta", pais_codigo: "CO" },
  { nombre: "Pitalito", pais_codigo: "CO" },
  { nombre: "Popayán", pais_codigo: "CO" },
  { nombre: "Quibdó", pais_codigo: "CO" },
  { nombre: "Riohacha", pais_codigo: "CO" },
  { nombre: "Rionegro", pais_codigo: "CO" },
  { nombre: "Sabanalarga", pais_codigo: "CO" },
  { nombre: "Sahagún", pais_codigo: "CO" },
  { nombre: "San Andrés", pais_codigo: "CO" },
  { nombre: "Santa Marta", pais_codigo: "CO" },
  { nombre: "Sincelejo", pais_codigo: "CO" },
  { nombre: "Soacha", pais_codigo: "CO" },
  { nombre: "Sogamoso", pais_codigo: "CO" },
  { nombre: "Soledad", pais_codigo: "CO" },
  { nombre: "Tibú", pais_codigo: "CO" },
  { nombre: "Tuluá", pais_codigo: "CO" },
  { nombre: "Tumaco", pais_codigo: "CO" },
  { nombre: "Tunja", pais_codigo: "CO" },
  { nombre: "Turbo", pais_codigo: "CO" },
  { nombre: "Valledupar", pais_codigo: "CO" },
  { nombre: "Villa de leyva", pais_codigo: "CO" },
  { nombre: "Villa del Rosario", pais_codigo: "CO" },
  { nombre: "Villavicencio", pais_codigo: "CO" },
  { nombre: "Yopal", pais_codigo: "CO" },
  { nombre: "Yumbo", pais_codigo: "CO" },
  { nombre: "Zipaquirá", pais_codigo: "CO" },
])


Empresa.create!([
  { nombre: "A.A.A" },
  { nombre: "ACA"},
  { nombre: "ADA"},
  { nombre: "AEROCIVIL"},
  { nombre: "AEROGAL"},
  { nombre: "AEROPOSTAL"},
  { nombre: "AEROREPUBLICA"},
  { nombre: "AEROSANIDAD"},
  { nombre: "AEXPA"},
  { nombre: "AIR PLAN"},
  { nombre: "AIRES"},
  { nombre: "AMERICAN AIRLINES"},
  { nombre: "AVIANCA"},
  { nombre: "BOMBEROS"},
  { nombre: "COMERCIO"},  
  { nombre: "CONSTRUCTORA"},
  { nombre: "COPA"},
  { nombre: "DEPRISA CARGA"},
  { nombre: "DESACOL"},
  { nombre: "EASY FLY"},
  { nombre: "EMPRESAS DE ASEO"},
  { nombre: "EMPRESAS DE VIGILANCÍA"},
  { nombre: "ENERGIZAR"},
  { nombre: "EQUIPAJEROS"},
  { nombre: "IDEAM"},
  { nombre: "INMIGRACIÓN - DIAN"},
  { nombre: "LAN"},
  { nombre: "LAS LOMAS"},
  { nombre: "LASA"},
  { nombre: "PANTURISMO"},
  { nombre: "PARTICULAR"},
  { nombre: "POLICIA"},
  { nombre: "RESTAURANTES"},
  { nombre: "SAI"},
  { nombre: "SANIDAD"},
  { nombre: "SATENA - FAC"},
  { nombre: "SIALAS"},
  { nombre: "SPIRIT"},
  { nombre: "TACA"},
  { nombre: "TAMPA"},
  { nombre: "TERPEL"},
  { nombre: "TRANSPORTADORES"},
  { nombre: "VIVA COLOMBIA"},
  { nombre: "VUELOS AMBULANCÍA"},
  { nombre: "VUELOS PARTICULARES"},
  { nombre: "ZONA DE CARGA"},
  { nombre: "OTROS"},


])


Aeropuerto.create!([
  { nombre: "Alfredo Vásquez Cobo", departamento: "Leticia", ciudad_id: 1},


])