class CreateClinicHistories < ActiveRecord::Migration
  def change
    create_table :clinic_histories do |t|
      t.string :first_name
      t.string :second_name
      t.string :first_surname
      t.string :second_surname
      t.string :email
      t.string :type_document
      t.string :document
      t.date :birthdate
      t.string :gender
      t.string :profession
      t.string :blood_type
      t.string :nacionality
      t.references :eps, index: true, foreign_key: true
      t.references :arl, index: true, foreign_key: true
      t.string :address
      t.integer :condition
      t.string :accompanist_name
      t.string :relationship
      t.string :phone
      t.references :city, index: true, foreign_key: true
      t.references :user, index: true, foreign_key: true
      t.string :city
      t.string :department
      t.references :user, index: true, foreign_key: true
      t.string :cove
      t.string :mobiel_service
      t.references :airport, index: true, foreign_key: true
      t.integer :type_service
      t.references :patient, index: true, foreign_key: true
      t.string :origin
      t.string :destination
      t.string :company
      t.string :accompanist_name
      t.integer :relationship
      t.string :phone
      t.text :reason_for_consultation
      t.text :current_illness
      t.boolean :neunatales_true
      t.boolean :neunatales_false
      t.text :neunatales_description
      t.boolean :patologicos_true
      t.boolean :patologicos_false
      t.text :patologicos_description
      t.boolean :quirurgicos_true
      t.boolean :quirurgicos_false
      t.text :quirurgicos_description
      t.boolean :farmacologicos_true
      t.boolean :farmacologicos_false
      t.text :farmacologicos_description
      t.boolean :alergicos_true
      t.boolean :alergicos_false
      t.text :alergicos_description
      t.boolean :toxicos_true
      t.boolean :toxicos_false
      t.text :toxicos_description
      t.boolean :traumaticos_true
      t.boolean :traumaticos_false
      t.text :traumaticos_description
      t.boolean :hospitables_true
      t.boolean :hospitables_false
      t.text :hospitables_description
      t.boolean :atep_laboral_true
      t.boolean :atep_laboral_false
      t.text :atep_laboral_description
      t.boolean :familiar_true
      t.boolean :familiar_false
      t.text :familiar_description
      t.boolean :inmunologicos_true
      t.boolean :inmunologicos_false
      t.text :inmunologios_description
      t.boolean :asociado_viajes_de_vuelo_true
      t.boolean :asociado_viajes_de_vuelo_false
      t.text :asociado_viajes_de_vuelo_description
      t.integer :menstrual_cycle
      t.string :gestational_age
      t.string :eco
      t.integer :fum
      t.boolean :pregnancy_true
      t.boolean :pregnancy_false
      t.string :g
      t.string :p
      t.string :c
      t.string :a
      t.string :m
      t.string :v
      t.string :e
      t.boolean :cardiovascular_true
      t.boolean :cardiovascular_false
      t.text :cardiovascular_description
      t.boolean :respiratory_true
      t.boolean :respiratory_false
      t.text :respiratory_description
      t.boolean :abdominal_true
      t.boolean :abdominal_false
      t.text :abdominal_description
      t.boolean :genito_urinario_true
      t.boolean :genito_urinario_false
      t.text :genito_urinario_description
      t.string :neurological_true
      t.string :neurological_false
      t.text :neurological_description
      t.boolean :mental_true
      t.boolean :mental_false
      t.text :mental_description
      t.boolean :sense_organ_true
      t.boolean :sense_organ_false
      t.text :sense_organ_description
      t.boolean :skeletal_muscle_true
      t.boolean :skeletal_muscle_false
      t.text :skeletal_muscle_description
      t.string :ta_mmgh
      t.string :heart_rate
      t.string :breathing_frequency
      t.string :sat_of_o_ambiente
      t.string :sat_of_o_supplementary
      t.string :temperature
      t.string :weight_in_kilograms
      t.string :height_in_centimeters
      t.boolean :head_true
      t.boolean :head_false
      t.text :head_description
      t.boolean :sense_organ_true
      t.boolean :sense_organ_false
      t.string :sense_organ_description
      t.boolean :neck_true
      t.boolean :neck_false
      t.text :neck_description
      t.boolean :rib_cage_true
      t.boolean :rib_cage_false
      t.text :rib_cage_description
      t.boolean :heart_true
      t.boolean :heart_false
      t.text :heart_description
      t.boolean :lungs_true
      t.boolean :lungs_false
      t.text :lungs_description
      t.boolean :abdomen_true
      t.boolean :abdomen_false
      t.text :abdomen_description
      t.boolean :genitourinary_true
      t.boolean :genitourinary_false
      t.text :genitourinary_description
      t.boolean :rectum_true
      t.boolean :rectum_false
      t.text :rectum_description
      t.boolean :extremities_true
      t.boolean :extremities_false
      t.text :extremities_description
      t.boolean :skin_and_appendages_true
      t.boolean :skin_and_appendages_false
      t.text :skin_and_appendages_description
      t.boolean :piel_y_faneras2_true
      t.boolean :piel_y_faneras2_false
      t.text :piel_y_faneras2_descripcion
      t.boolean :skeletal_muscle_true
      t.boolean :skeletal_muscle_false
      t.text :skeletal_muscle_description
      t.boolean :mental_true
      t.boolean :mental_false
      t.text :mental_description
      t.boolean :neurological_true
      t.boolean :neurological_false
      t.text :neurological_description
      t.integer :alteration
      t.integer :eye_opening
      t.integer :verbal_answer
      t.integer :motor_response
      t.integer :other_signs
      t.text :analysis
      t.text :print_diagnosed
      t.text :plan_and_treatment
      t.text :observations_recommendations

      t.timestamps null: false
    end
  end
end
