require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Cie10sController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Cie10. As you add validations to Cie10, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Cie10sController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all cie10s as @cie10s" do
      cie10 = Cie10.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:cie10s)).to eq([cie10])
    end
  end

  describe "GET #show" do
    it "assigns the requested cie10 as @cie10" do
      cie10 = Cie10.create! valid_attributes
      get :show, {:id => cie10.to_param}, valid_session
      expect(assigns(:cie10)).to eq(cie10)
    end
  end

  describe "GET #new" do
    it "assigns a new cie10 as @cie10" do
      get :new, {}, valid_session
      expect(assigns(:cie10)).to be_a_new(Cie10)
    end
  end

  describe "GET #edit" do
    it "assigns the requested cie10 as @cie10" do
      cie10 = Cie10.create! valid_attributes
      get :edit, {:id => cie10.to_param}, valid_session
      expect(assigns(:cie10)).to eq(cie10)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Cie10" do
        expect {
          post :create, {:cie10 => valid_attributes}, valid_session
        }.to change(Cie10, :count).by(1)
      end

      it "assigns a newly created cie10 as @cie10" do
        post :create, {:cie10 => valid_attributes}, valid_session
        expect(assigns(:cie10)).to be_a(Cie10)
        expect(assigns(:cie10)).to be_persisted
      end

      it "redirects to the created cie10" do
        post :create, {:cie10 => valid_attributes}, valid_session
        expect(response).to redirect_to(Cie10.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved cie10 as @cie10" do
        post :create, {:cie10 => invalid_attributes}, valid_session
        expect(assigns(:cie10)).to be_a_new(Cie10)
      end

      it "re-renders the 'new' template" do
        post :create, {:cie10 => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested cie10" do
        cie10 = Cie10.create! valid_attributes
        put :update, {:id => cie10.to_param, :cie10 => new_attributes}, valid_session
        cie10.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested cie10 as @cie10" do
        cie10 = Cie10.create! valid_attributes
        put :update, {:id => cie10.to_param, :cie10 => valid_attributes}, valid_session
        expect(assigns(:cie10)).to eq(cie10)
      end

      it "redirects to the cie10" do
        cie10 = Cie10.create! valid_attributes
        put :update, {:id => cie10.to_param, :cie10 => valid_attributes}, valid_session
        expect(response).to redirect_to(cie10)
      end
    end

    context "with invalid params" do
      it "assigns the cie10 as @cie10" do
        cie10 = Cie10.create! valid_attributes
        put :update, {:id => cie10.to_param, :cie10 => invalid_attributes}, valid_session
        expect(assigns(:cie10)).to eq(cie10)
      end

      it "re-renders the 'edit' template" do
        cie10 = Cie10.create! valid_attributes
        put :update, {:id => cie10.to_param, :cie10 => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested cie10" do
      cie10 = Cie10.create! valid_attributes
      expect {
        delete :destroy, {:id => cie10.to_param}, valid_session
      }.to change(Cie10, :count).by(-1)
    end

    it "redirects to the cie10s list" do
      cie10 = Cie10.create! valid_attributes
      delete :destroy, {:id => cie10.to_param}, valid_session
      expect(response).to redirect_to(cie10s_url)
    end
  end

end
